### ISSUE TITLE
Define Recording Limit

### ISSUE THREAD

**Issue by HomerJayAllTheWay** [elan-ev/opencast-studio#1013]
Are there any recording limits for OpenCast Studio in terms of length or file size? If so, it would be nice if the Opencast Studio could define a limit to the length or size of the recording or give the user some indication of how long of a recording they can capture based on the available disk space of their device.

**Comment by LukasKalbertodt** [comment]
I don't know of any artificial limitations by browsers. The only limitation I can think of is the exhaustion of disk space, which the browser can't really do anything about.

I assume you are a programmer; if that's not the case please correct me. Your GitHub profile is very empty, so it's hard to judge :)
Under that assumption: the main API relevant here is [`MediaRecorder`](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder). We pass media streams into it acquired by [`getUserMedia`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) and/or [`getDisplayMedia`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia). But yeah, the actual recording is done by `MediaRecorder`. And I can't find any useful information about disk space exhaustion in the MDN docs or in the specification.
