### ISSUE TITLE
add config for using studio within multiple moodle instances

### ISSUE THREAD

**Issue by fsufrre** [elan-ev/opencast-studio#1014]
As disscused with @LukasKalbertodt at the summit it would be nice to use opencast studio within multiple moodle tenants.
Therefore its neccessary to differentiate from which moodle instance opencast studio is called from.

The suggestion was to add a certain config url parameter for each moodle instance.

**Comment by LukasKalbertodt** [comment]
To add a bit more context and refresh my memory: in your case, some configuration values have to be different for the different Moodle tenants. In particular, I think you talked about setting a custom `upload.acl` or `upload.dcc`. 
As I mentioned, you can specify almost all configuration parameters via query parameter in the URL; and you can also specify the full config there as a hex-encoded string. But when setting `acl` or `dcc`, it is understandable that putting that into the URL is not ideal as the URL would be very long.

So you said in your use case, you can just place one config TOML file into `/ui/config/studio/` *per* moodle instance, right? So the idea would be to have a new query parameter `configPath` (or sth like that) which lets you specify a different path of config file on the same server. I think that was the idea?
