### ISSUE TITLE
Hidden download functionality

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#102]
In the media upload dialog, you can click on a preview image to download that specific video. I would never have found this if I hadn't spotted this in the code. In other words: This function must get a clear marking. This could, for example, be a download icon in the bottom-right corner of the preview image.

**Comment by luniki** [comment]
This got added by you and @sivagurucse 
Should this be included or can should it be reverted?

**Comment by LukasKalbertodt** [comment]
I think this was fixed long ago. There is a download button for weeks already. The whole "post recording" dialog needs to be reworked again anyway, but I think we can close this issue for now.
