### ISSUE TITLE
AV Sync Issues on Windows 10 and 11 when using Hardware Acceleration

### ISSUE THREAD

**Issue by HomerJayAllTheWay** [elan-ev/opencast-studio#1029]
I'm running into an issue with recording on Windows PC's with a GPU. The audio sync is off by ~1 second. This happens on high-powered developer workstations (e.g. i8 with 64GB of RAM) and AMD Radeon Pro GPU. It also happens on my Microsoft Surface Laptop running Windows 11. Switching browsers between Chrome and Firefox doesn't seem to make much of a difference.

The only way to get proper AV Sync on these devices is to disable "Use hardware acceleration when available" in the browser.

Any ideas why this may be occurring or how to correct the issue without having to manually enable/disable hardware acceleration before recording on this type of device?

**Comment by LukasKalbertodt** [comment]
Interesting. Can you test whether the issue also occurs [on this page](https://addpipe.com/media-recorder-api-demo/)?

**Comment by HomerJayAllTheWay** [comment]
When testing on that page, the A/V I get from that is in sync. I re-enabled hardware acceleration before testing and I can see that the .webm is encoded with H.264. Without web acceleration the file was encoded in VP9.

I'll test on some other laptops/device today or tomorrow.

**Comment by LukasKalbertodt** [comment]
Did the issue fully resolve with the update?

**Comment by HomerJayAllTheWay** [comment]
Yes it fixed the issue. Thanks for checking in on this.
