### ISSUE TITLE
Do not rely on foreign session cookies

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#103]
The authentication mechanism already fails in some browsers if the main domain of the tool and the Opencast server differs (e.g. localhost vs opencast.org). The situation will soon be worsened when Chrome implements the announced changed to hew they handle foreign cookies:

> (index):1 A cookie associated with a cross-site resource at https://develop.opencast.org/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Finally, there is no reason to use a session at all since we keep the credentials in memory anyway and we can just use HTTP Basic authentication.

**Comment by luniki** [comment]
Mit der aktuellen Konfiguration ist CORS und HTTP Basic Auth nicht möglich. Wird der CORS preflight fetch gesendet, antwortet Opencast mit 302 und einer Umleitung auf das Login. Damit bricht der CORS preflight fetch standardkonform ab, da kein 2xx Code geliefert wurde.

**Comment by luniki** [comment]
Ich stelle vorsichtig trotzdem erst einmal auf axios um, dann wird es später besser wartbar.

**Comment by lkiesow** [comment]
Can you avoid German in here? I know it's kind of unusual coming from the Stud.IP community but it's rude against non-German community members.

The CORS Header configuration is recommended in the about page. Can you make a new recommendation? I can then deploy it to all test servers.

**Comment by luniki** [comment]
Oh, sorry. 

Ok, I guess that this is quite difficult. The CORS headers aren't the problem.

The problem is Opencast answering with a 302 to an OPTIONS request instead of a 200 status code.

**Comment by lkiesow** [comment]
Okay, so we stuck on OPTIONS, but that's still something we could have Nginx answer (or we can pull this into Opencast). To decide on a way forward, what would be your expected result for an OPTION request? A 200 with no content and all necessary headers? Is there any OPTIONS request where you would expect something else (e.g. content from Opencast)?

**Comment by luniki** [comment]
For an example have a look at  https://developer.mozilla.org/de/docs/Glossary/Preflight_request [https://developer.mozilla.org/de/docs/Glossary/Preflight_request] 


Wed Oct 30 16:41:44 GMT+01:00 2019 Lars Kiesow <notifications@github.com>:

**Comment by luniki** [comment]
This issue cannot be solved without support on the OC side. Either there should be changes to the nginx conf or OC has to do this on its own.

**Comment by LukasKalbertodt** [comment]
Closed by #455
