### ISSUE TITLE
Incomplete translations

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#1072]
Some translation don't cover all texts (Greek, Farsi), shortcuts are in English most of the time and the settings are only partially translated:

![grafik](https://github.com/elan-ev/opencast-studio/assets/1752342/bf2c21b7-618f-4d73-a228-8340f80e8e9b)

**Comment by LukasKalbertodt** [comment]
Yes, that's unfortunately true. It might be worth asking the wider community for translation help again after the redesign is finished. Unfortunately, some languages have hardly any translations left. So I think asking the community for help and then throwing out "barely translated languages" would be a good idea.

**Comment by LukasKalbertodt** [comment]
Quick update:
- I cleaned translation files in #1135 (that's just internal refactoring)
- The same PR also removed two languages that had hardly any translations left (Greek and Turkish)
- I asked Farbod (a colleague) about providing a full Farsi translation. He plans on finishing that this or next week.
- I asked Miguel (Paella dev) about a full Spanish translation. He provided it already and it's now included in Studio. See #1138 
- I asked the person who provided Chinese simplified before, whether they could update it. No reply yet.
- I am planning on enabling Crowdin for Studio again, hopefully making translation a lot easier for translators.

**Comment by LukasKalbertodt** [comment]
Lots of translations were provided. I think this issue can be closed. The Crowdin stuff is tracked by #492
