### ISSUE TITLE
Shortcuts page, law of proximity violated / leads to wrong assumptions

### ISSUE THREAD

**Issue by ClemensGruber** [elan-ev/opencast-studio#1078]
On Studio's shortcuts page (click in the header section on any page at "shortcuts") the law of proximity is violated and leads so to wrong assumptions, bad orientation and so suboptimal usability: 

The law of proximity declares that you perceive closely positioned elements as belonging together. So ALT+S seems to be the shortcut for "show this overview" and not the question mark. 

![2023-08-25 10_39_31-Opencast Studio – Mozilla Firefox3](https://github.com/elan-ev/opencast-studio/assets/36139413/fcb3d263-6414-46f2-8b24-f0c628c674d2)

But that is not the right funcion for ALT+S but "Show available shortcuts". 

![2023-08-25 10_39_31-Opencast Studio – Mozilla Firefox2](https://github.com/elan-ev/opencast-studio/assets/36139413/2322d372-4d59-4066-bfed-66d73c999c5f)

With the huge distance between the desciption and the belonging keys a person with magnification software as assistive technologie may also run in trouble because it is difficult to see descriptiion and keys on a high magnification level together: 

![2023-08-25 11_16_55-Opencast Studio – Mozilla Firefox](https://github.com/elan-ev/opencast-studio/assets/36139413/7e56bb18-2d66-4957-95cf-2de02e84b899)

The keys are also not consistant, some elements are stacked Alt+S, some abreast Ctrl+<-, there is also a inconsistancy because some combinations have a "+" sign between the keys, some not: 

![2023-08-25 10_39_31-Opencast Studio – Mozilla Firefox4](https://github.com/elan-ev/opencast-studio/assets/36139413/1fc97278-a97d-46a1-ba35-8a3bc1333577)

I would 
- not use two columns and 
- change the order of key and description, first key(s) (check if right aligned is better than left), then description 
- add a "+" sign between every combination so it is clear that it is the same

**Comment by LukasKalbertodt** [comment]
> The keys are also not consistant, some elements are stacked Alt+S, some abreast Ctrl+<-, there is also a inconsistancy because some combinations have a "+" sign between the keys, some not:

That's because the keys on top of each other are actually alternatives, not combinations. So you can press either "alt" or "S" to "show available shortcuts". Buuut I agree that this might not be clear.

And yes, I can understand your other points as well. I will have to try to come up with some other design that's better in these regards and hopefully looks better too.

**Comment by ClemensGruber** [comment]
Ahh, Alt or S, I see! So a simple "or" may help in this case!
