### ISSUE TITLE
Waveform appearance in dark mode

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/opencast-studio#1096]
@lkiesow wrote in https://github.com/elan-ev/opencast-studio/pull/1069#issuecomment-1691166632:

> ![Screenshot from 2023-08-24 09-22-45](https://github.com/elan-ev/opencast-studio/assets/1008395/c63564a0-7736-4b74-b902-377022021b5f)
>
> I think the black waveform box looks a bit odd. Especially since there is already a box around that box. Can we try switching to the same background color as the inner box? Something like this:
>
> ![Screenshot from 2023-08-24 09-22-45](https://github.com/elan-ev/opencast-studio/assets/1008395/48fd2cf1-a302-4ea8-ae98-3301abbf7107)

@oas777 replied in [TODO](https://github.com/elan-ev/opencast-studio/pull/1069#issuecomment-1691208011):

> I consider this a canvas holding a box (cf. editor) and I wouldn't want this removed, at least not in the light mode:
> ![grafik](https://github.com/elan-ev/opencast-studio/assets/1752342/820d36b1-411e-4322-b8e2-7b7b4fe7f53e)

Discuss!

**Comment by LukasKalbertodt** [comment]
Personally, I don't think it's a problem and I would just keep it as is. If no one else will comment here agreeing with Lars in the next while, I will close this issue (to clean the issue list a bit).

**Comment by narickmann** [comment]
I would leave it as it is. Without the box, it feels like sth is missing (at least a border).
As a compromise, you could make the box a little brighter (i.e. a dark gray, but only in dark mode)? But then we could have too little contrast.

**Comment by lkiesow** [comment]
I think what's weird is that you essentially have a box in a box, with both having a different background color.
