### ISSUE TITLE
Navigation in the last step is potentially confusing/inconsistent

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/opencast-studio#1099]
@lkiesow wrote in https://github.com/elan-ev/opencast-studio/pull/1069#issuecomment-1691174090:

> ![Screenshot from 2023-08-24 09-25-25](https://github.com/elan-ev/opencast-studio/assets/1008395/99578491-fb3c-49ec-a825-7ccd2c44d833)
>
> Does it make sense to have a back button on the last page if the previous one has a discard and start again? Wouldn't prople maybe want to restart a recording from here as well?

@oas777 replied in https://github.com/elan-ev/opencast-studio/pull/1069#issuecomment-1691214500:

> Probably. Which makes me ask why I have to up-/ or download before I can actually press "Start a new recording".

@LukasKalbertodt replied in https://github.com/elan-ev/opencast-studio/pull/1069#issuecomment-1691246311:

> What if people want to change the cut points or check something again? I can easily imagine someone first skipping the review step, then writing metadata, and then remembering that they had to cut something or check if one can hear the cat screaming in the background, or something like that.
>
> In my head, the main situations where someone wants to start a new recording are:
>
> They want to discard because something went wrong. They will notice that during recording or in the review step, not in the last step. And there they immediately have a button to do that.
> They want to start a new recording after having saved their current one. And that only makes sense after saving their current one.
> And for those few cases that fall outside of these two situations, users have to click one additional time to start a new recording. I don't really see the problem here, to be honest.

@oas777 replied in https://github.com/elan-ev/opencast-studio/pull/1069#issuecomment-1691392910:

> I could suggest for "Start a new recording" to appear not until the recording has been up- or downloaded, but then, I don't feel strongly about this. Enjoy your holidays!

**Comment by LukasKalbertodt** [comment]
> I could suggest for "Start a new recording" to appear not until the recording has been up- or downloaded, but then, I don't feel strongly about this. Enjoy your holidays!

I don't understand this, can you elaborate?

As I stated in my comment, I don't really see the problem here. So unless someone can explain it to me, I would close this issue soon-ish (to clean the issue list a bit).
