### ISSUE TITLE
Workflows (from server)should be selectable 

### ISSUE THREAD

**Issue by rrolf** [elan-ev/opencast-studio#11]
currently the workflow is set with it's ID in the configuration dialog of the server.

I would prefer a dropdown with available workflows in the upload dialog. 
I would recommend a "studio" tag for workflows in Opencast. If the studio-tag is existing at all, we show only these workflows, if not all "upload" workflows are shown.

**Comment by luniki** [comment]
How does one get a list of suitable workflows?

**Comment by lkiesow** [comment]
I don't think we necessarily can. At least not if we don't want to extend the required privileges for users to use this.

If we want people to have at least access to the admin interface, we could use the [admin interface REST endpoint](https://develop.opencast.org/admin-ng/event/new/processing?tags=upload) but that one is not stable and I wouldn't. If we want sane selections for specific installations, we could provide a list to which people could contribute and set their own installation URL plus preferred settings.

**Comment by lkiesow** [comment]
Note that this requires a very high level of privileges:

https://github.com/elan-ev/opencast-studio/blob/968f87531e52ed9ccd140375a4f34128e37a7cc0/src/opencast-uploader.js#L210-L214

**Comment by LukasKalbertodt** [comment]
We recently decided to not let the user decide about the workflow. The target audience of this tool very likely does not know about workflows and can't reasonably decide. The workflow ID is still configurable via settings, just not via UI.
