### ISSUE TITLE
Do we need a button to delete a cut marker?

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/opencast-studio#1101]
@JasminNovotni wrote in https://github.com/elan-ev/opencast-studio/pull/1069#issuecomment-1669585824:

> * We miss the button for deleting the cut marker.

@LukasKalbertodt replied in 

> (Note: The shortcut to delete the marker still exists.)
> How do others feel about this? Can you provide a "user story" of how the lack of this delete button is annoying?

Discuss!

**Comment by narickmann** [comment]
I don't have "a "user story" of how the lack of this delete button is annoying", but I think the button is no longer necessary. 

We can now move the little toggle (with the square bracket) back and forth. If we move it to the beginning, we no longer have a cut mark (cut mark = deleted).

Yes, maybe it's faster to click a button, but we also have shortcuts for that (and as I said, we can move it to the start/end).

So IMO we don't necessarily need the button anymore.

**Comment by lkiesow** [comment]
I think keeping the tool as simple as possible is good. Having less button helps. I don't thing we need buttons for this.

First, it's pretty much an edge case that someone decides to cut a video, tinkers with the cut marks (and actually defines some) but then decides to not cut after all. Most of the time, I expect people to completely ignore the step, or realize during the review, that setting cut marks is not necessary.

If someone still ends up in the situation that cut marks are set, but they want the whole video, there is also already an easy solution: Set the beginning to 0 and the end to the video end. It may not be as convenient in that situation compared to a button which does the same thing automatically, but we are talking about something, barely any user will end up in.

**Comment by LukasKalbertodt** [comment]
Most are in favor of keeping it as is. Thus closing.
