### ISSUE TITLE
Is it confusing that you have to pause the recording before you can stop it?

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/opencast-studio#1102]
@JasminNovotni wrote in https://github.com/elan-ev/opencast-studio/pull/1069#issuecomment-1669585824:

> It's confusing that you have to pause the recording before you can stop it. Having an extra pause and stop button still makes sense to me.

@oas777 agrees in https://github.com/elan-ev/opencast-studio/pull/1069#issuecomment-1675051252:

> I feel the same butI also can see Lukas argument to make it harder to accidentally stop when you want to pause.

Discuss!

**Comment by LukasKalbertodt** [comment]
Since there hasn't been any further discussion about this and most people seem fine with this, I will close this issue now.
