### ISSUE TITLE
The warning triangle in case of a technical problem when sharing content seems lonely

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/opencast-studio#1103]
@oas777 wrote in https://github.com/elan-ev/opencast-studio/pull/1069#issuecomment-1675100147:

> The warning triangle in case of a technical problem when sharing content seems lonely: Could we integrate it into the (upper right corner) of the warning text?

to which @LukasKalbertodt replied in https://github.com/elan-ev/opencast-studio/pull/1069#issuecomment-1686631451:

> Imagine the warning triangle being a placeholder for the video what would have appeared there. That was the idea anyway.
What do others think about this? Moving this would be easy.

Poor warning triangle. 😦

**Comment by narickmann** [comment]
The triangle maybe looks a bit lonely, right, but I still think it makes sense as an eye-catcher, that something happened and needs my attention. (The red colour itself already does this, but the triangle emphasizes it)

If we put the triangle in the notification or into the corner, we might have too much empty/unused space. Not sure, if I like this.

![Bildschirmfoto](https://github.com/elan-ev/opencast-studio/assets/93541078/4584999a-7a07-4e6f-9dbb-5174afeec4f5)

Could this be an alternative: making the notification itself more central (and perhaps larger)? In the middle of the video element?

I like the little triangle as it is. But I'm also open to other suggestions.

**Comment by oas777** [comment]
Interestingly, this doesn't look too bad:

![grafik](https://github.com/elan-ev/opencast-studio/assets/1752342/a93e7b7e-908e-4822-801f-77c6b4e1d1be)

**Comment by narickmann** [comment]
Yeah, this could be a solution. Maybe with a bit less strong red? 

Maybe like this? It's still catchy but less aggressive (This is now 300px and the color is danger1)

![grafik](https://github.com/elan-ev/opencast-studio/assets/93541078/612f50ee-65d4-47e8-b7e7-e3303fb730e0)

**Comment by oas777** [comment]
Yeah, obviously mine was just a suggestion to understand the dimensions. Yours is much better.

**Comment by oas777** [comment]
That's even better (and closer to my original suggestion).

**Comment by LukasKalbertodt** [comment]
What do you all thinkg about #1113?

**Comment by oas777** [comment]
@lkiesow will surely complain about "a box in a box"...

**Comment by narickmann** [comment]
> What do you all think about https://github.com/elan-ev/opencast-studio/pull/1113?

For smaller screens this may look good and fits better. But for larger screens I think the box around the notification is too small. 

I think the larger box in Lars' suggestion looks better.
