### ISSUE TITLE
Do we need/want the resolution/aspect ratio/... settings?

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/opencast-studio#1104]
@oas777 wrote in https://github.com/elan-ev/opencast-studio/pull/1069#issuecomment-1675100147:

> Can people comment on the relevance of the resolution settings? They don't seem to work most of the time (Windows/Firefox), but maybe others have a different experience. If so, could we make them customizable?

@LukasKalbertodt replied in https://github.com/elan-ev/opencast-studio/pull/1069#issuecomment-1686631451:

> I am very aware that these settings often don't work and are generally pretty shitty. (That's not our fault -- the browsers simply don't give us more control.) However, I still think it's very useful.
>
> A very concrete example: when I create a video with Studio, I would share my 4k screen. Chrome by default downscales to 1080p, so there I will manually select 2160p to make it work. For the webcam, I will select 4:3 aspect ratio instead of the standard 16:9 to show less of my room and more of my face. So I've actually used these options and I don't think I'm the only one. Further, I think the settings button is small enough to not be intrusive: most users can just ignore it. The settings are hidden by default. So personally, I'm strongly for keeping all of this.
>
> But of course, I'm also interested in what others say.

**Comment by narickmann** [comment]
I'll leave my thoughts here.

I agree with Lukas. The settings button is not too present and distracting. If anyone needs these settings they are available and if you don't need them you can just ignore the button. Also there is a hint, that these settings could not work and I think that someone who uses these settings is aware of that?

I've tested a bit and these settings seem to work on my system (Linux and Chrome - in Firefox too, except for the camera aspect ratio).

So IMO we should keep these settings.

**Comment by oas777** [comment]
So let's keep them - but make sure it's easier to "just ignore the button" by making it less obtrusive: Maybe a semi-transparent grey background instead of the black one?

![grafik](https://github.com/elan-ev/opencast-studio/assets/1752342/8eea57e7-a7be-4a45-89d9-c9576967dfe0)

**Comment by narickmann** [comment]
> Maybe a semi-transparent grey background instead of the black one?

It already is transparent. Depending on whether the background is light or dark, the colors are inverted (for higher contrast).

![grafik](https://github.com/elan-ev/opencast-studio/assets/93541078/a7af366b-73b2-47f6-8db3-aa490bf28aaa) ![grafik](https://github.com/elan-ev/opencast-studio/assets/93541078/bd24a9df-b912-45d2-888f-1cf6787d02c1) ![grafik](https://github.com/elan-ev/opencast-studio/assets/93541078/31968f44-480b-45ad-9283-96b2733be710)

**Comment by oas777** [comment]
Admittedly, it is transparent. But not unobtrusive:
![grafik](https://github.com/elan-ev/opencast-studio/assets/1752342/d7953045-ba8f-4ee4-bccf-aa8b9d9d79b5)
![grafik](https://github.com/elan-ev/opencast-studio/assets/1752342/253a50ab-93a6-4fc1-ae33-eb6a65aa1cdd)
