### ISSUE TITLE
Firefox (Windows) doesn't show sharing options when only sharing the display

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/opencast-studio#1106]
@oas777 wrote in https://github.com/elan-ev/opencast-studio/pull/1069#issuecomment-1675100147:

> * Firefox (Windows) doesn't see Chrome to share when I only want to share the display - it works though when I share display and camera. Can others confirm this?

@oas777 I hope I didn't misunderstand you; maybe check whether the title correctly represents your issue.

**Comment by oas777** [comment]
Couldn't reproduce this, so you can close the ticket.
