### ISSUE TITLE
Invalid keyboard shortcuts are being suggested

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#1115]
Not all keyboard shortcuts suggested by the overlays are correct. For example, the overlay suggested hitting `D` to download. But hitting `D` doesn't actually work. You need to use `d` instead.

![Screenshot from 2023-09-22 00-42-39](https://github.com/elan-ev/opencast-studio/assets/1008395/dd48bb75-7bf4-42f3-950c-bdef58a61df9)

**Comment by LukasKalbertodt** [comment]
Oh that's a good point. All letter-keys are shown as uppercase, but this was not intended to imply shift has to be pressed. I didn't consider this source of confusion. So I will probably simply show letters as lowercase I suppose?
