### ISSUE TITLE
root tarballs not working?

### ISSUE THREAD

**Issue by majosch** [elan-ev/opencast-studio#1151]
The root-flavor tarball from the latest release [oc-studio-2023-11-20-root.tar.gz](https://github.com/elan-ev/opencast-studio/releases/download/2023-11-20/oc-studio-2023-11-20-root.tar.gz) is not working? Because my browser wants to load studio from https://main.bundle.js/

In the index.html file the links to the stylesheets seem to be wrong?

```
<link rel="stylesheet" href="./font.css"><link rel="icon" href="//favicon.ico"><script defer="defer" src="//main.bundle.js"></script>
```
When building studio without `export PUBLIC_PATH=/` the studio app loads fine.

**Comment by LukasKalbertodt** [comment]
Thanks for catching that! I swear I tested this. But oh well, somehow I screwed this up. I created https://github.com/elan-ev/opencast-studio/pull/1152 to fix this. After this is merged, I will release a new release.

**Comment by LukasKalbertodt** [comment]
The tarball is fixed in https://github.com/elan-ev/opencast-studio/releases/tag/2023-12-06
