### ISSUE TITLE
Cannot open "Share desktop" on Firefox 69.0.2 Windows 10

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#144]
With the latest Firefox update, I cannot stop screen sharing pressing the "Share desktop" button. The "Share webcam" button works. Both buttons work with Chrome.

**Comment by luniki** [comment]
Do you mean "stop screen sharing" or "start screen sharing"?

**Comment by oas777** [comment]
I cannot start the screen sharing.

**Comment by luniki** [comment]
Is this on localhost or on studio.opencast.org?

Are there any error messages in the web developer console?

**Comment by luniki** [comment]
Did you modify the about:config settings?

**Comment by oas777** [comment]
studio.opencast.org. The web console says:

interactive selection.js:23:13
Tab url: https://studio.opencast.org/ selection.js:91:17
Path name: / selection.js:92:17
Domain: studio.opencast.org selection.js:93:17
complete selection.js:24:65
Click event triggered:
mouseup 0 false selection.js:107:31
Error:NotAllowedError: The request is not allowed by the user agent or the platform in the current context. media-devices.js:10:12
Click event triggered:
mouseup 0 false selection.js:107:31
Error:NotAllowedError: The request is not allowed by the user agent or the platform in the current context. media-devices.js:10:12

​

**Comment by luniki** [comment]
Did you choose a window or a screen from the dropdown before clicking on "Allow"?

![image](https://user-images.githubusercontent.com/2993/67754325-8ea70800-fa36-11e9-9480-136514f96494.png)

**Comment by oas777** [comment]
No. But I just realised that Firefox blocked screen sharing after the update without asking me. Should have thought of that, sorry.

**Comment by luniki** [comment]
There is still a UX problem: If I click on allow w/o choosing a window or screen, I cannot start screen sharing again. FF "knows" that I did not allow anything and does not trigger the "Will you allow <URL> to see your screen?" again.

There should be visual feedback that I intentionally chose to NOT share my screen. At the very least the "Share screen" megabutton should not be seemingly active.
