### ISSUE TITLE
Think about and document browser support

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/opencast-studio#155]
We should probably explicitly think about and then eventually stipulate and document which browsers we want to support.

See also the `browserlist` setting in `package.json`, which is still `crreate-react-app`-s default, if I'm not mistaken. Is this default sensible (for our use cases)?

**Comment by LukasKalbertodt** [comment]
We briefly talked about this today. We want to support:

- Desktop: Firefox, Chrome, Edge
- Android: Firefox, Chrome
- iOS: Safari

In particular, we do not care about IE. Of each of those browser, we want to support the two or three most recent versions.
