### ISSUE TITLE
Define Branching Model

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#156]
The branching model should look like this:

```
        deployment on studio.opencast.org
                  ^      ^          ^
                  |      |          |
production -------*------*----------*-->
                 /      /          /
master --*---*--*----*-*----------*-->
          \   \/    /   \        /
patch-1 .  *--*\   /     \      /
patch-2 .  .  . *-*       \    /
patch-3 .  .  .  .  .  .   *--*
```

– The branch `production` is automatically deployed to [studio.opencast.org](https://studio.opencast.org)
- The branch `master` is a *safety* before deploying live with test deployment (*to be discussed*)
- The branch `master` will be merged into `production` as often as possible
- Pull requests from other branches should be created against `master`
- `master` will be the default branch

**Comment by LukasKalbertodt** [comment]
In the diagram it looks like each time a patch is merged into `master`, it is also merged into `production`, but that's not necessarily true, right? We probably merge `master` into `production` less often than patches are merged into `master`, right? 

Apart from that, I like the branching model!

**Comment by lkiesow** [comment]
I slightly adjusted the graph but please always merge from `master` to `production` unless QA showed there is a problem.

This branching structure is now in place:

- `master` is the default branch
- `react` hast been removed
- `production` will automatically be deployed
