### ISSUE TITLE
Studio should work in a sub-path

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#158]
Deployed under `/build`, I get the following errors:

```
2.d2bdc9fc.chunk.js:1 Failed to load resource: the server responded with a status of 404 (File not found)
main.48876d58.chunk.js:1 Failed to load resource: the server responded with a status of 404 (File not found)
:8000/manifest.json:1 Failed to load resource: the server responded with a status of 404 (File not found)
:8000/manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
```

**Comment by luniki** [comment]
You have to build opencast-studio with the correct parameter:

PUBLIC_URL=/build npm run build

More about this in the create-react-app documentation.

**Comment by lkiesow** [comment]
No, it still does not work. Even with `PUBLIC_URL` exported.
See the deployment at:

- https://test.studio.opencast.org/build-388/

and the build log at (expand “Deploying application”):

- https://travis-ci.com/elan-ev/opencast-studio/jobs/255358303

**Comment by luniki** [comment]
I am on it.

**Comment by luniki** [comment]
As soon as #172 gets merged this will be closed.
