### ISSUE TITLE
Set (webcam) resolution

### ISSUE THREAD

**Issue by rrolf** [elan-ev/opencast-studio#16]
Is there a way to change the webcam resolution? currently this seems to be 480p while the screen recording resolution seems to be my real screen resolution.

I would like to adjust both manually if needed. My webcam could be useful also with higher resolutions, and contrary if I have a notebook with 4K resolution recording this in 720p might be more reliable and faster.

**Comment by luniki** [comment]
After commit a42f904 this is not yet selectable but clicking on "Share webcam" requests a video source with this constraints:
```

      video: {
        width: { ideal: 1280, max: 1920 },
        height: { ideal: 720, max: 1080 }
      }

```
