### ISSUE TITLE
Use accessible notifications

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#164]
These short-lived notification pop-ups are an accessibility nightmare:

![Screenshot from 2019-11-06 11-36-52](https://user-images.githubusercontent.com/1008395/68291792-e115a380-008a-11ea-9e5e-50b02cbf07d1.png)

If you need visual aid, you are likely to miss them.

**Comment by luniki** [comment]
Will be fixed in 2ffcaa6 as soon as the PR is finally merged.

**Comment by luniki** [comment]
Now that the PR is merged this issue can be closed.
