### ISSUE TITLE
Add options to enable/disable and configure Google Analytics

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/opencast-studio#169]
We briefly touched on that in our small meeting earlier today. We three seem to be in favor of removing it. Any reasons not to?

**Comment by luniki** [comment]
There is issue #33 

Perhaps Rüdiger knows more about it.

**Comment by LukasKalbertodt** [comment]
Rüdiger said he'd like to keep it for the `studio.opencast.org` but that adding a configuration to optional enable it would be fine.

**Comment by lkiesow** [comment]
It would be nice to have this as a build option so that we could e.g. disable analytics if we build for Opencast

**Comment by lkiesow** [comment]
Maybe we could still throw out Google Analytics despite what @rrolf said and just use Cloudflare's proxy analysis which we could easily turn on for the public site. That would make the whole thing simpler and we do not need any custom, special-case code for this.

**Comment by rrolf** [comment]
I am fine with couldflare log analytics too, although I would prefer one tool as GA is already in use. 

I can only say regarding the board meeting yesterday that we need to know better about our users. Whenever we approach commercial companies they want to know more about the market.

**Comment by lkiesow** [comment]
I'll check if Cloudflare is a valid option.

**Comment by lkiesow** [comment]
We get less information from cloudflare. @rrolf, having seen the information, do you think that those are sufficient for the board? If yes, we can drop this. If no, we need to quickly design an option to exclude this for the inclusion in Opencast.

**Comment by LukasKalbertodt** [comment]
Closed by #453
