### ISSUE TITLE
Specify Series

### ISSUE THREAD

**Issue by rrolf** [elan-ev/opencast-studio#17]
Selecting a series will be specifically relevant in the context of LTI & co. In this case, we want to automatically provide the series, e.g. via a `?series=` URL parameter.

---

Original comment:
<details>
<strike>
In the upload dialog I would like to have an option to see the series' the server and select them if appropriate. 

It would also be great to be able to provide a series with an URL GET parameter (from an external tool).
</strike>
</details>

**Comment by luniki** [comment]
How does one get a list of all the series of a server?

**Comment by luniki** [comment]
Related to #35

**Comment by lkiesow** [comment]
Note that this requires a relatively high level of privileges to work:

https://github.com/elan-ev/opencast-studio/blob/968f87531e52ed9ccd140375a4f34128e37a7cc0/src/opencast-uploader.js#L204-L208

**Comment by LukasKalbertodt** [comment]
Implemented in #470
