### ISSUE TITLE
Collect used Web APIs to communicate required browser versions

### ISSUE THREAD

**Issue by luniki** [elan-ev/opencast-studio#173]
While debugging OC Studio on iOS I once again found another compatibility problem with the MediaRecorder API.

We have to collect every used Web API to  communicate required browser versions.

**Comment by luniki** [comment]
https://caniuse.com/#feat=mediarecorder

![image](https://user-images.githubusercontent.com/2993/68748982-c3ea5300-05fd-11ea-8e5a-cc9a87f30fd4.png)

**Comment by luniki** [comment]
https://caniuse.com/#feat=serviceworkers

![image](https://user-images.githubusercontent.com/2993/68749201-1f1c4580-05fe-11ea-9b3b-6a929c10066c.png)

**Comment by luniki** [comment]
https://caniuse.com/#feat=mdn-api_mediadevices_getusermedia

![image](https://user-images.githubusercontent.com/2993/68749882-3f98cf80-05ff-11ea-8874-0d35f130e873.png)

**Comment by luniki** [comment]
https://caniuse.com/#feat=mdn-api_mediadevices_getdisplaymedia

![image](https://user-images.githubusercontent.com/2993/68749972-6951f680-05ff-11ea-97bb-357d903d5543.png)

**Comment by luniki** [comment]
Furthermore some older browsers do not implement the srcObject field defined in the HTMLMediaElementAPI

**Comment by luniki** [comment]
The Media Recording API alone requires:
* IE: нет
* Edge: v76+
* Safari: 13 (or 12.1 with a special flag enabled)

**Comment by luniki** [comment]
In this iPad's Safari I had to enable the MediaRecorder experimental flag though it is v13.x :cry:

**Comment by LukasKalbertodt** [comment]
I think our up-to-date browser support matrix in the README is sufficient. Sure, a list of used APIs would be nice, but also hard to maintain, probably large and most importantly: not interesting for most users. So let's close this for now.
