### ISSUE TITLE
Add polyfill for oldschool MediaDevices#getUserMedia

### ISSUE THREAD

**Issue by luniki** [elan-ev/opencast-studio#179]
See for example:

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Using_the_new_API_in_older_browsers

**Comment by LukasKalbertodt** [comment]
Given that we decided to only support fairly up-to-date versions of Firefox, Chrome, Edge and Safari (see [README](https://github.com/elan-ev/opencast-studio/tree/832c44d9f3737de134c67067e1d241ebe4dc9eeb#supported-browsers)), I think we can close this, right?

**Comment by luniki** [comment]
Yes your are right
