### ISSUE TITLE
Add special treatment for missing srcObject field

### ISSUE THREAD

**Issue by luniki** [elan-ev/opencast-studio#180]
Some Browsers do not implement the HTMLMediaElement API in regards to the `srcObject`. Work around this using the `src` field!

**Comment by LukasKalbertodt** [comment]
Related: #241

**Comment by LukasKalbertodt** [comment]
Given #170, it seems like all browsers we want to support also support `srcObject`. [caniuse.com about this feature](https://caniuse.com/#feat=mdn-api_htmlmediaelement_srcobject). I tested it on iOS Safari, so it works there, too. 

So maybe we can simply close this issue?

**Comment by luniki** [comment]
Sure.
