### ISSUE TITLE
Let the user decide whether or not to include the cursor in the screen recording

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/opencast-studio#185]
The JS API allows to specify whether or not the cursor should be included. I think the user should be able to choose as both choices do make sense in certain situations, right?

**Comment by lkiesow** [comment]
Include it by default. This is a good addition for a future “advanced mode”

**Comment by luniki** [comment]
This feature is currently not supported (only Opera does). The video track's settings says: cursor=always. But one just cannot constrain this in any way.

**Comment by luniki** [comment]
See: https://caniuse.com/#feat=mdn-api_mediatrackconstraints_cursor
