### ISSUE TITLE
Provide "Cancel" option for settings 

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#196]
If you active settings, the overlay opens to configure the Opencast settings. The only way to close this is to press "Validate Settings". If the users presses "settings" by accident and doesn't know what to do, he needs an additional button to leave this overlay ("Cancel").

**Comment by LukasKalbertodt** [comment]
This should be fixed by #223, right @luniki?

**Comment by luniki** [comment]
@LukasKalbertodt: This is correct :+1:
