### ISSUE TITLE
Windows 10, Firefox 70, two screens: Sharing Chrome appears black in Opencast Studio

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#197]
![studio-2](https://user-images.githubusercontent.com/1752342/68929104-e7430880-078b-11ea-91fe-b71eb5832cb2.png)

**Comment by oas777** [comment]
PS: In this image, it's white actually.

**Comment by oas777** [comment]
When selecting the second screen (with Chrome on it) instead of Chrome (as an application), it works.

**Comment by LukasKalbertodt** [comment]
I doubt this has anything to do with Opencast Studio, as the screen capturing is completely implemented by the browser, not by our code. So this seems to be a bug in Firefox or Windows. 

Could you test this behavior with [this test page](https://www.webrtc-experiment.com/getDisplayMedia/) by clicking "Test getDisplayMedia API". That page uses the same browser functionality as we do. I suspect you will see the same behavior as with Opencast Studio, meaning that it has nothing to do with our code.

**Comment by oas777** [comment]
Did the test: Trying to share Chrome as a programme resulted in a black square (studio-1), sharing the monitor Chrome is displayed on gives you a preview to Chrome (studio-2). Both ways, sharing them with this test page leads to an error message (studio-3).
![studio-3](https://user-images.githubusercontent.com/1752342/69035199-5fefd200-09e3-11ea-9ecf-60dd790240ef.png)
![studio-2](https://user-images.githubusercontent.com/1752342/69035200-5fefd200-09e3-11ea-8870-1ce89ebaa364.png)
![studio-1](https://user-images.githubusercontent.com/1752342/69035202-5fefd200-09e3-11ea-8846-e27b1184e92a.png)

**Comment by oas777** [comment]
PS: Again, when capturing this, the black square turns into a white one.

**Comment by LukasKalbertodt** [comment]
So, if I understand correctly, the behavior is the same for the other website. The website fails with an error, but in the preview window you can also observe the buggy behavior. In that case, it indeed has nothing to do with Studio, but just with the browser. So I will close this issue. If I misunderstood something, please let me know!

And just as an idea for the potential cause for this strangeness: Chrome recently enabled an experimental feature called "WebContent Occlusion". I saw it in the news as this apparently broke a few things for certain users. But I don't know any details.
