### ISSUE TITLE
Windows 10, Firefox 70: Doesn't find Logitech camera attached via USB

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#198]
Studio only detects the built-in camera and selects it without asking for another option. BBB and whereby can see two cameras and let me choose or automatically go for the USB camera I selected earlier.
![studio-3](https://user-images.githubusercontent.com/1752342/68929506-ca5b0500-078c-11ea-8a2e-1bdd1c5d44ea.png)
![whereby](https://user-images.githubusercontent.com/1752342/68929515-cdee8c00-078c-11ea-803a-0b9587ed08f0.png)
![bbb](https://user-images.githubusercontent.com/1752342/68929516-cdee8c00-078c-11ea-8c67-ccfc7ddad409.png)

**Comment by LukasKalbertodt** [comment]
To the best of my knowledge, Opencast Studio itself is not involved in detecting webcams at all. That's all implemented by the browser. 

Could you please try to revoke the pages permission, reload and try again? I suspect that you at some point selected the wrong webcam and clicked "remember that decision". In that case, Firefox won't ask again. You can revoke the site's permission to the webcam by clicking left to the URL bar and then clicking the X next to the "allowed" label.

![image](https://user-images.githubusercontent.com/7419664/68960037-a0770200-07cf-11ea-80a5-d7cec1722631.png)

(Sorry for phone picture of computer screen; my screenshot utility didn't let me make a picture of that popup. :grin:)

Please let us know if that fixed it for you!

For reference, mobile Firefox does not have a "Remember that decision" box.

**Comment by oas777** [comment]
Testing three websites I use with my camera(s): The permissions are not the problem for Opencast Studio (studio-1) and they are the same with https://whereby.com/id.mms.ethz (studio-2) which then automatically uses the USB camera (due to me using it regularly, I presume). http://matterhorn.bigbluebutton.org/matterhorn/ does it best in that it asks what camera to use (studio-3).  All tested with the latest Firefox on Windows 10.
![studio-3](https://user-images.githubusercontent.com/1752342/69035690-86623d00-09e4-11ea-8442-83e188f61c00.png)
![studio-2](https://user-images.githubusercontent.com/1752342/69035692-86623d00-09e4-11ea-851b-afbbdc1e6bad.png)
![studio-1](https://user-images.githubusercontent.com/1752342/69035693-86623d00-09e4-11ea-9fed-62c6038d5f96.png)

**Comment by LukasKalbertodt** [comment]
Thanks for testing! Have you tried *revoking* the permissions for Studio, reloading and trying again? As you said yourself, wheryby uses your USB camera automatically because you once said "Remember that decision". I assume you checked the "Remember that decision" for Studio, too, but chose the wrong camera input. Revoking the permissions should fix that.

**Comment by oas777** [comment]
You were right! Revoking the permission, then reloading the page resulted in the website / Opencast Studio asking what camera to use, cf. studio-1. 
![studio-1](https://user-images.githubusercontent.com/1752342/69055985-5714f580-0a0f-11ea-97cb-e2c0a73eed84.png)

**Comment by LukasKalbertodt** [comment]
Perfect :)
