### ISSUE TITLE
Change the selected source ex post

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#199]
Once you made a choice to select a screen or an application, there is no way to change that (same for webcams if you have two of them). There should be an option to change your decision by selecting again. Or at least an "Cancel" option to start the selection process again.

**Comment by LukasKalbertodt** [comment]
Just to be clear, you want to change the selected video source before you started recording and not while recording, right? 

You can always just reload the page, but I agree that this is not great for usability. Especially for less technically-versed users.

**Comment by oas777** [comment]
Yes, I would like to change this before the recording starts. This might help if you 
a) selected the wrong source by accident or
b) decide to change the source once you see it in the preview.

And yes, reloading is not a good option for this.

**Comment by Melanie-Koller** [comment]
And i like to change the video source while recording. For example if i have a presentation and then i like to show a video. Or if i closed the window of my presentation by accident.

**Comment by luniki** [comment]
> And i like to change the video source while recording. For example if i have a presentation and then i like to show a video. Or if i closed the window of my presentation by accident.

If I understand the algorithms detailed in the MediaStream Recording API (https://w3c.github.io/mediacapture-record/#MediaRecorderAPI) correctly, it is not possible to add, remove or change MediaStream tracks as soon as recordings started. So I guess it is technically not feasable to do this.

Disregarding the API specification it is certainly very hard to change the dimensions of a video stream while recording (for example at first recording my whole 4K monitor and then switching to a very small browser tab).

**Comment by luniki** [comment]
> Once you made a choice to select a screen or an application, there is no way to change that (same for webcams if you have two of them). There should be an option to change your decision by selecting again. Or at least an "Cancel" option to start the selection process again.

This will be easy as soon as #288 got merged

**Comment by LukasKalbertodt** [comment]
Fixed by #288
