### ISSUE TITLE
Countdown is too short and should be a real countdown ("3...2...1")

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#201]
Plus, there should be audio.

**Comment by LukasKalbertodt** [comment]
Hi there! Could you elaborate why you would like to have sound effects for the countdown? I could imagine many other users might be annoyed by sound effects.

**Comment by oas777** [comment]
Happy to do so: The countdown is to tell you when the recording starts. Without audio, you only get a visual information on the time remaining and you have to look at the countdown indicator to see that - which means you don't look at the camera. Which is what you should be doing when the recording starts! So an audio indicator of the time remaining is helpful when looking at the camera, maybe three "beeps" with the last one (one second before the recordings starts) a bit louder than the first two.

**Comment by LukasKalbertodt** [comment]
Thanks! That makes sense. I somehow assumed that all videos recorded by Studio would be cut afterwards anyway (in which case you could just start talking whenever). But yes, if you don't want to do any editing after recording, a countdown with sound makes sense. Thanks for the suggestion!

**Comment by LukasKalbertodt** [comment]
For now we removed the useless 1s countdown in #452 . The larger issue of "how do we remove the first few useless seconds of recording" is now tracked by #454.
