### ISSUE TITLE
Windows 10, Edge: Studio doesn't show anything

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#209]
This is what I see (admittedly, it's an administered computer, but that shouldn't be the problem):
![studio-1](https://user-images.githubusercontent.com/1752342/69035857-e9ec6a80-09e4-11ea-8b46-18556118f9c2.png)

**Comment by lkiesow** [comment]
Microsoft is just about to replace their browser backend and Edge will auto-update to the new rendering engine in ~2 months. We should test with the new version which is already available and not focus on the old one which is going away anyway.

That sais… we need to test with the new Edge beta.

**Comment by luniki** [comment]
Which version of Edge is it?

**Comment by oas777** [comment]
Microsoft Edge 44.18362.449.0

**Comment by luniki** [comment]
My guess is that since #170 OC Studio does not support the JS engine of Microsoft Edge prior to v76 but as I currently have no access to an Edge v44, I cannot verify this.

@lkiesow @LukasKalbertodt: Do you have access?

**Comment by lkiesow** [comment]
You can get a Windows device for testing from my office.
It's the surface tablet behind my desk.
If you need it, just take it if I'm not in my office.
But we need it back for testing ;-)

**Comment by LukasKalbertodt** [comment]
This immediate bug is fixed by #241. With that, you can capture the camera. However, recording is not possible yet. This is now tracked by #242.
