### ISSUE TITLE
About page with references to the original developers 

### ISSUE THREAD

**Issue by rrolf** [elan-ev/opencast-studio#21]

**Comment by lkiesow** [comment]
Here is some test for the about page:

---

# Opencast Studio

A web-based recording studio for [Opencast](https://opencast.org).

This is free software under the terms of the [MIT license](https://github.com/elan-ev/opencast-studio/blob/master/LICENSE) developed by the [ELAN e.V.](https://elan-ev.de) in cooperation with the [ETH Zürich](https://ethz.ch). Please report bugs or submit new features on the project's [GitHub page](https://github.com/elan-ev/opencast-studio).

If you are interested in additional development or integrations into specific tools (e.g. LMS), please contact [opencast-support@elan-ev.de](mailto:opencast-support@elan-ev.de).

## Credits

Thanks to the following people and institutions for contributing to this project:

- [Duncan Smith](https://github.com/slampunk) for starting this project
- [University of Cape Town (CILT)](https://github.com/cilt-uct) for letting Duncan start the project
- [ETH Zürich](https://ethz.ch) for financial support and testing
- [ELAN e.V.](https://github.com/elan-ev) for the final development

---

```
# Opencast Studio

A web-based recording studio for [Opencast](https://opencast.org).

This is free software under the terms of the [MIT license](https://github.com/elan-ev/opencast-studio/blob/master/LICENSE) developed by the [ELAN e.V.](https://elan-ev.de) in cooperation with the [ETH Zürich](https://ethz.ch). Please report bugs or submit new features on the project's [GitHub page](https://github.com/elan-ev/opencast-studio).

If you are interested in additional development or integrations into specific tools (e.g. LMS), please contact [opencast-support@elan-ev.de](mailto:opencast-support@elan-ev.de).

## Credits

Thanks to the following people and institutions for contributing to this project:

- [Duncan Smith](https://github.com/slampunk) for starting this project
- [University of Cape Town (CILT)](https://github.com/cilt-uct) for letting Duncan start the project
- [ETH Zürich](https://ethz.ch) for financial support and testing
- [ELAN e.V.](https://github.com/elan-ev) for the final development
```
