### ISSUE TITLE
Disable all links while recording

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/opencast-studio#211]
While recording, you should only be able to pause/resume and stop the recording. Accidentally clicking/tapping on a link should not actually do anything because that would cancel the recording. Especially on mobile devices I would imagine that can happen easily.

**Comment by luniki** [comment]
I am not sure how you want to communicate this to user? Without proper feedback this will cause support effort.
Perhaps the recording page should not contain these links at all?

**Comment by lkiesow** [comment]
Removing them would work and may also give us additional screen real estate. The other option would be to simply gray them out:

![Screenshot from 2020-02-08 14-11-33](https://user-images.githubusercontent.com/1008395/74085792-2b893080-4a7d-11ea-8e62-5d79b351013f.png)
