### ISSUE TITLE
Do not dismiss the post-recording dialog when pressing "upload" or "save media"

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/opencast-studio#213]
Some people would potentially like to do both, download the file then upload it. The dialog should only be dismissed manually by pressing "Cancel" (which might change to "Finish" once the video has either been up- or downloaded).

**Comment by lkiesow** [comment]
I like that idea. But this also means that we need a good feedback mechanism for uploads and a proper way of closing the dialog.

**Comment by LukasKalbertodt** [comment]
Fixed by #288
