### ISSUE TITLE
Mobile Safari and Chrome always use front face camera without asking

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/opencast-studio#217]
Firefox. on the other hand, always lets the user chose. So I'm not sure if we can actually do something about that on the JS side. In the worst case we need to implement a dialog to let the user chose.

**Comment by luniki** [comment]
We can even do this afterwards. That should be no problem at all. The "old" ghettostudio allowed for this but it was removed to streamline the experience even before I transfered the code into a React app.

**Comment by LukasKalbertodt** [comment]
This also affects Edge.

**Comment by LukasKalbertodt** [comment]
Currently we [request the front face camera via the constraints](https://github.com/elan-ev/opencast-studio/blob/41be5a34279ffaa27726825aeb11b34a2370fae6/src/ui/studio/video-setup/index.js#L45). However, without requesting anything specific, Chrome just uses the back-facing camera without asking.
