### ISSUE TITLE
Include Version/Build Number

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#220]
If possible, builds should include the following information in the about page:

- build date
- commit hash
- CI build number
- maybe commit title?

**Comment by LukasKalbertodt** [comment]
Instead of the commit title, I think it would be more useful to link to the specific commit on Github. There one can see the title and lots of other stuff. So maybe something like this:

> Version: [`5e3d953`](https://github.com/elan-ev/opencast-studio/commit/5e3d95330912578a77758c47ee2a95bbd0e425c5) (2019-11-19)

And yeah, potentially also the CI build number.
