### ISSUE TITLE
Error in Browser console "Uncaught (in promise) TypeError: Request method 'POST' is unsupported"

### ISSUE THREAD

**Issue by rrolf** [elan-ev/opencast-studio#26]
After uploading a recording to Opencast, I see this error 4 times in the logs of the browser

Uncaught (in promise) TypeError: Request method 'POST' is unsupported
    at sw.js:22
(anonymous) @ sw.js:22
Promise.then (async)
fetchAndUpdate @ sw.js:21
Promise.then (async)
(anonymous) @ sw.js:9
Promise.then (async)
(anonymous) @ sw.js:7

**Comment by lkiesow** [comment]
I think this has already been resolved
