### ISSUE TITLE
Audio waveform in opencast

### ISSUE THREAD

**Issue by Melanie-Koller** [elan-ev/opencast-studio#279]
There is no audio waveform visible in opencast.

**Comment by LukasKalbertodt** [comment]
We already have an issue for this #30. In case you were talking about Opencast and not Opencast Studio, this issue can be closed, too, as it needs to be reported elsewhere (and I don't know anything about waveform in Opencast). Thanks for the report anyway!

**Comment by lkiesow** [comment]
> In case you were talking about Opencast and not Opencast Studio, this issue can be closed, too, as it needs to be reported elsewhere (and I don't know anything about waveform in Opencast).

To elaborate on this, the fast testing workflow you chose for the processing in Opencast never generates waveforms for Opencast's video editor. That is a deliberate choice to allow for faster processing. Waveforms are in fact optionally for the editor.
