### ISSUE TITLE
Opencast go back to studio

### ISSUE THREAD

**Issue by Melanie-Koller** [elan-ev/opencast-studio#280]
If i'm in opencast, how can i go back to the studio? Can there be a button?

**Comment by LukasKalbertodt** [comment]
You can always use your browser's "back" button to go back, but I agree that we could improve things. However, I doubt that adding a button on the Opencast side will be a good solution. 

@lkiesow @luniki Should we maybe remove the "go to Opencast" button completely? Are target users expected to work with the Opencast admin interface? Should it be configurable whether or not the button is shown? Should clicking the button open Opencast in a new tab/window automatically?

**Comment by LukasKalbertodt** [comment]
We will at some point add a button to the Opencast Admin UI that links to Studio. But since that's not really part of this project and because of the things mentioned above, I will close this issue.
