### ISSUE TITLE
Improve uploading/handling of long recordings

### ISSUE THREAD

**Issue by Melanie-Koller** [elan-ev/opencast-studio#282]
For longer presentations (+50 min.) the upload to opencast is during more than 30 min.

**Comment by LukasKalbertodt** [comment]
Uploading large video files might indeed take a long time. I guess we should add some kind of progress bar. And someone should investigate if the long upload times are actually justified by file size or if our app is inefficient in some way.

**Comment by luniki** [comment]
As soon as we will have ported the upload/download dialog into a separate page we can visualize upload progress esp well.

**Comment by LukasKalbertodt** [comment]
Blocked by https://github.com/elan-ev/opencast-studio/issues/377

**Comment by luniki** [comment]
Unblocked?
