### ISSUE TITLE
Processing of videos with odd resolutions fails in Opencast

### ISSUE THREAD

**Issue by Melanie-Koller** [elan-ev/opencast-studio#284]
I tried to capture in my presentation adobe photohop and adobe premiere. The result is processing failure in opencast. Save media is working.

**Comment by lkiesow** [comment]
The problem seems to be the odd video resolution of 2560x1337 or specifically the height of 1337 which does not work with a 4:2:0 chroma subsampling used in the fast workflow. This is no studio but an Opencast problem. I'll fix that.

**Comment by lkiesow** [comment]
Fix for Opencast: opencast/opencast#1269

**Comment by lkiesow** [comment]
Fixed in Opencast
