### ISSUE TITLE
Define download preferences

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#300]
The preference all refer to Opencast but you cannot define where the downloads go. This should be part of the preference menue, maybe separated from the Opencast settings in different tabs. 

Alternative from #302: Or it could be defined by the user in the post-recording dialog.

**Comment by lkiesow** [comment]
Download dialogs asking for locations and the lack of them is part of the browser interfaces which cannot easily be controlled by websites. They can usually be set by users in their browser preferences. Therefore, we cannot really do anything about this.

**Comment by oas777** [comment]
Can't you automatically take me to the dialog I get when I use the context menu and choose "Download link" / "Download target as"? This takes me to my default download folder, but I can also go to other folders.

**Comment by lkiesow** [comment]
I don't think we can. This is a fixed setting in browsers:

Firefox:
![Screenshot from 2020-02-08 15-03-48](https://user-images.githubusercontent.com/1008395/74086597-98ec8f80-4a84-11ea-9e65-dfc39fa0839f.png)

Chromium:
![Screenshot from 2020-02-08 15-04-49](https://user-images.githubusercontent.com/1008395/74086608-b883b800-4a84-11ea-80d3-85cd442a68b5.png)

So, users can turn it on. But they have to turn it on on their own.
