### ISSUE TITLE
Download to nowhere?

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#301]
Currently, downloading media after recordings does not produce a file in the download folder defined by the browser. Tested on OS X (Firefox) and Windows 10 (Firefox).

**Comment by LukasKalbertodt** [comment]
I tested it with the current version of studio.opencast.org and with Firefox on Windows 10 and it seems to work. Firefox asks if I want to open or save the file. Chrome just saves the file. I cannot test on OS X, but I doubt that Firefox behaves differently there. So I will close this for now. If it is in fact not fixed yet, we can reopen.

**Comment by oas777** [comment]
Confirmed.
