### ISSUE TITLE
Workflow  problems

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#304]
Two of my recordings from today have ended in a workflow problem ("Snagit...").

**Comment by LukasKalbertodt** [comment]
I realize it's probably a bit late for that, but: can you reproduce this problem? If so, how? 

At first glance this sounds like a problem with the OC installation and not with OC Studio. In that case the issue could be closed. @lkiesow @luniki What do you think?

**Comment by oas777** [comment]
I think the problem is still there because my upload just now (screen only, Firefox on Windows) resulted in a "Vearbeitungsfehler", cf. screenshot.
![oc](https://user-images.githubusercontent.com/1752342/73030219-7417db80-3e39-11ea-94b6-5c445824ae42.jpg)

**Comment by lkiesow** [comment]
The problems should be fixed withion the workflow used by default in Opencast Studio.
