### ISSUE TITLE
Opencast date problem?

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#305]
Why do all the recordings available at 

https://develop.opencast.org/admin-ng/index.html#!/events/events?storage=%7B%22pagination%22:%7B%22events%22:%7B%22resume%22:false,%22limit%22:10,%22offset%22:0%7D%7D,%22sorter%22:%7B%22events%22:%7B%22title%22:%7B%22name%22:%22title%22,%22priority%22:0,%22order%22:%22ASC%22%7D%7D%7D%7D

have all the same date every time I test Opencast Studio?

**Comment by LukasKalbertodt** [comment]
In this test Opencast server (notice the **`develop.`**`opencast.org`), all videos get removed once a day, as this is just for testing and permanent storage is not necessary. That probably explains why all recordings always have the date "today".

Does this answer your question? Or am I missing something?

**Comment by oas777** [comment]
Absolutely.
