### ISSUE TITLE
Select webcam if more than one exists

### ISSUE THREAD

**Issue by darolfes** [elan-ev/opencast-studio#31]

**Comment by luniki** [comment]
Shouldn't this be done by the user using the dialog from the user agent?

**Comment by darolfes** [comment]
I don't know the details, this was only reported to me. You probably need to test this with multiple webcams.

**Comment by luniki** [comment]
I tested this in desktop and mobile environments but could not reproduce any problems. I close this for now until we get more detailed error reports.
