### ISSUE TITLE
Show link to admin UI if the user (from `info/me`) can access it

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/opencast-studio#313]
Currently, a link to the admin UI is always shown in the toolbar. This is not really optimal as "standard users" should not be able (or required) to access it. We should only include that link of the user has the correct roles (`ROLE_ADMIN`?) to access it.

**Comment by lkiesow** [comment]
The role would be `ROLE_ADMIN_UI`

**Comment by LukasKalbertodt** [comment]
With #674, a more flexible solution was merged. Closing.
