### ISSUE TITLE
We need a legal notice

### ISSUE THREAD

**Issue by rrolf** [elan-ev/opencast-studio#32]

**Comment by lkiesow** [comment]
This should probably do:

---

# Impressum

ELAN e.V. (E-Learning Academic Network)

Dr. Norbert Kleinefeld, Geschäftsführer
Karlstr. 23
D-26123 Oldenburg

URL: https://elan-ev.de
E-Mail: kontakt@elan-ev.de
Telefon: +49 441 998 666 10


Registergericht: Amtsgericht Oldenburg
Registernummer: VR 200644
USt.-ID-Nr.: DE 265901392
