### ISSUE TITLE
Integrate storybook to develop components in isolation

### ISSUE THREAD

**Issue by luniki** [elan-ev/opencast-studio#324]
Developing a react application with a lot of UI components, it is hard to see the different states these components can be in when the components are integrated into the app. To develop components and see all their states in isolation we should add storybook support. 

This is very easy. Have a look at https://storybook.js.org/docs/basics/introduction/

**Comment by LukasKalbertodt** [comment]
We decided not to do that anymore because the project is nearly finished.
