### ISSUE TITLE
Flickering behind the upload dialog

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/opencast-studio#328]
When editing the title in the upload dialog, the "share desktop" panel, which can still be seen in the background, flickers on every keystroke.

It's kinda hard to put into words, and can probably better be seen in this short clip I just made:

https://imgur.com/ppSPM57

The flickering is not visible on every key stroke in the video because filming screens is hard. It was definitely there on every keystroke, though.

In another test I just did, which I didn't film, though, the aspect ratio of the thing changed as well... :thinking:

**Comment by luniki** [comment]
As soon as PR #288 gets approved we do not have any modals anymore and this issue can be closed.

**Comment by LukasKalbertodt** [comment]
#288 landed.
