### ISSUE TITLE
Media recording broken

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#335]
![Screenshot from 2019-12-31 13-52-16](https://user-images.githubusercontent.com/1008395/71622735-3330fc00-2bd8-11ea-8211-e0f3d58e7a4c.png)

Select a screen recording, start the recording, finish the recording and you will end up in the upload dialog where under media **no** media is present.

**Comment by lkiesow** [comment]
Additional information

- This seems to happen only for screenrecordings
- This seems to happen only in Firefox
- Recording a webcam works as expected
- Recordings screen and webcam will result in a webcam video only

**Comment by LukasKalbertodt** [comment]
(CC @luniki as this is related to the bug I mentioned in #288)

I found the cause of this. This is our list of codecs:

```
            'video/webm;codecs="vp9,opus"',
            'video/webm;codecs="vp9.0,opus"',
            'video/webm;codecs="avc1"',
            'video/x-matroska;codecs="avc1"',
            'video/webm;codecs="vp8,opus"'
```

My FF does not support the first 4 and thus uses `video/webm;codecs="vp8,opus"`. vp8 is the video codec, opus is the audio codec. If the stream given to the `MediaRecorder` does not contain audio, but an audio codec is specified in the mimetype, FF's `MediaRecorder` just does not start. Calling `.start()` on it does not do anything, in particular `onstart` and `onstop` are not called. 

Curiously, the `.start()` call does not throw and exception and also does not call our `onerror` handling. So it seems like this is a FF bug? 

We can work around this by simply adding `'video/webm;codecs="vp8"'` as possible codec before the one with `opus`. But we should probably have a separate list of codecs for the "only video, no sound" case. I will improve our codec selection next week and still try to find out if this bug (or strange behavior) has been reported to FF already.

**Comment by LukasKalbertodt** [comment]
It looks like we don't have a lot of choices in this regard. Chrome and Firefox only support WEBM (and MKV, which is just a superset of WEBM) as container format. See [these answers](https://stackoverflow.com/q/41739837/2408867), for example. Both browsers support VP8 and VP9 as video codec. Chrome also supports H264 and AVC1 as video codec (Firefox doesn't), but I don't think that solves the "Apple problem". (I will check that as soon as I get my hands on an Apple device.)

As already noted, users of Apple devices can download software to play WEBM files. It's just not built in.

My completely personal opinion on this is to ignore the issue as it's just Apple refusing to add support for WEBM and related codecs. WEBM and MKV are [basically the only free (as in Open Source license and not patent-encumbered), widely used container formats](https://en.wikipedia.org/wiki/Comparison_of_video_container_formats). The video codecs used in WEBM are [also freely available](https://en.wikipedia.org/wiki/Comparison_of_video_codecs). We see Apple's refusal to support open standards in a few other areas as well (e.g. Vulkan). I don't see why we should invest any time in "fixing" this. This is clearly Apple's choice.
