### ISSUE TITLE
Settings are contained in a very narrow column in Firefox

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#336]
Firefox

![Screenshot from 2019-12-31 13-49-40](https://user-images.githubusercontent.com/1008395/71622977-a71fd400-2bd9-11ea-8014-50d03cc696d2.png)

Chrome

![Screenshot from 2019-12-31 13-49-39](https://user-images.githubusercontent.com/1008395/71622978-a71fd400-2bd9-11ea-9ebc-a9c210933111.png)

**Comment by LukasKalbertodt** [comment]
On `master`, both browsers show settings in narrow column. I guess we should define some fixed width with `max-width: 95%` or something like that. Will fix this issue after #289 is merged, as that already touches the settings page.

**Comment by lkiesow** [comment]
Revising my complaint, what's actually different is the size between the settings which pop up automatically at the beginning and the setting after you click on the gear icon. You can confirm this if you open studio in a new private tab.

**Comment by LukasKalbertodt** [comment]
This has been fixed at some point. (a) settings are not shown on start anymore, (b) the margins/spacing looks the same on both browsers now.
