### ISSUE TITLE
Two "identical" videos, two qualities, two files sizes

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#358]
I recorded two screencasts within a couple of minutes with the same setting on Windows 10 (recording Firefox from Chrome). Resulting files are very different in size - and quality, cf. attachments. What happened?

[Downloads.zip](https://github.com/elan-ev/opencast-studio/files/4092735/Downloads.zip)

**Comment by lkiesow** [comment]
One effect I have seen is Chrome adjusting the encoding settings on-the-fly according to system load. This can lead to videos which change their resolution even in the same video. It's basically adaptive recording. This might be the effect here as well.

**Comment by LukasKalbertodt** [comment]
I will go ahead and close this issue as there is not really anything we can do. We can tell Chrome about some codec parameters (via the MIME type) and a target bitrate. Both of these things are configurable via settings (see `CONFIGURATION.md`). We don't want to show those options to the user as that would be way too advanced for our target users. In the end, we always have to kind of trust the browser in encoding.
