### ISSUE TITLE
Wrong response status code to OPTIONS requests

### ISSUE THREAD

**Issue by luniki** [elan-ev/opencast-studio#377]
To receive upload progress events Opencast has to answer with a 200 status code to any preflight request (method = "OPTIONS").

Instead Opencasts sends a 302 redirect to the login, because preflight "OPTIONS" requests must not contain cookies and must not be authenticated.

This has to be configured on the nginx side.

**Comment by LukasKalbertodt** [comment]
This should be fixed by https://github.com/opencast/opencast-project-infrastructure/pull/2

This is only for the public Opencast instances of course.
