### ISSUE TITLE
Recording contines after stopping recording

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#393]
When stopping a recording, this will not actually stop the recording but seemingly continue to take the video inputs which is somewhat confusing, especially since recording-lights and indications still continue to indicate to users that there is something wrong with them stopping the recording.

![___________xxxxxxxxxx____IMG_20200205_144717__01](https://user-images.githubusercontent.com/1008395/73847880-68f48080-4827-11ea-9235-4b65e5ed963f.jpg)

**Comment by LukasKalbertodt** [comment]
This is already tracked by #379. But yes, I'm probably also in favor of releasing the webcam.
