### ISSUE TITLE
Update Content-Security-Policy

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#40]
It currently contains a number of unnecessary rules.

**Comment by luniki** [comment]
Currently the rules are:

`<meta http-equiv="Content-Security-Policy" content="default-src 'self' wss:; connect-src 'self' blob: https: ws: wss: studio.letmedev.com:443 wss://studio.letmedev.com; style-src 'self' https://kit-free.fontawesome.com https://fonts.googleapis.com ; media-src 'self' blob:; img-src 'self' data:; font-src 'self' data: https://fonts.gstatic.com https://kit-free.fontawesome.com; script-src 'self' https://kit.fontawesome.com">`

What should the rules be?

**Comment by lkiesow** [comment]
I'm pretty sure that we can at least remove `studio.letmedev.com` as well as all of the WebSocket allowances. More if we include fontawesome.

**Comment by LukasKalbertodt** [comment]
This issues seems to be outdated. Currently we do not specify `Content-Security-Policy` at all, if I'm not mistaken. I'll just close this now.
