### ISSUE TITLE
“Next”-button on video selection page

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#401]
There is a next button on the video selection page although the only way to actually get to the next view is selecting a video source which will automatically forward you to the next view.

**Comment by LukasKalbertodt** [comment]
This issue, #394 and #400 all stem from the same "misunderstanding".

The wizard was designed/intended to be a 4 step process: (1) video select, (2) audio select, (3) recording, (4) post-recording. In that context, the "next" button, the title and the "reselect source" button make sense. *However*, as it has become very clear now, the user perceives the video selection as two separate steps. The UI changes a lot between the three buttons (desktop, cam, both) and the preview of the selected video source, so it is understandable.

Not only is this inconsistent with the audio selection (as mentioned [here](https://github.com/elan-ev/opencast-studio/issues/395)), but in this 5 step process, the "next" button, title and "reselect source" button indeed do not make sense!

So yes, there is some design/UX work to do.

**Comment by oas777** [comment]
I'm not sure I agree because I like the four-step-process and I think it's consistent except for https://github.com/elan-ev/opencast-studio/issues/403 and some other minor issues (https://github.com/elan-ev/opencast-studio/issues/405, colors, position of "Back" and "Next").
