### ISSUE TITLE
Going back from the recording screen will not keep your audio settings

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#402]
Going back from the recording screen will not keep your audio settings and you have to re-select if you want to record audio while the video selection is being kept. That's a weirdly inconsistent behavior.

**Comment by LukasKalbertodt** [comment]
This only happens if you selected "no audio". If you got an audio stream, returning to the audio selection has the "microphone" button already activated. But yes, that's obviously still a bug :D
