### ISSUE TITLE
UX around uploading to Opencast (confirmation text, button color, user help)

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#407]
1. There are two confirmations, "Upload complete!" up there, "Uploaded to Opencast!" in the button used to upload.
2. Grey is a very strange color to confirm upload, especially with two different greys.
3. After uploading to Opencast, there is no option to actually go to Opencast. Or any information on what happens to the recording.

**Comment by LukasKalbertodt** [comment]
This should be fixed now (by several PRs).

1. The upload button is hidden after the upload succeeded.
2. The upload button is green now.
3. Now it at least says "Opencast now processes your recording" or something like that. A link to the admin UI is tracked by #313 and better post-upload texts is tracked by #480
