### ISSUE TITLE
Windows 10, Chrome: Studio doesn't detect external camera - Wherby.com does!

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#442]
[Chrome camera.zip](https://github.com/elan-ev/opencast-studio/files/4260710/Chrome.camera.zip)

Whereby sees my Logitech, Studio does not. Browser history was deleted beforehand.

**Comment by LukasKalbertodt** [comment]
In your video, we unfortunately can't see the popup by Chrome where you can select your camera. But in any case, I already have a suspicion why Studio is buggy here. I will soon work on improving the whole "let the user select a good camera" situation. Also to fix #217

**Comment by oas777** [comment]
That's the point: There was no pop-up to select the camera, Chrome chose the internal camera automatically.

**Comment by LukasKalbertodt** [comment]
I see. Just to be sure, this is not the same issue as [this one](https://github.com/elan-ev/opencast-studio/issues/198)? Have you tried the solution to the previous issue?

**Comment by oas777** [comment]
To the best of my knowledge: It's not the same problem. But then, I can be pretty stupid sometimes.

**Comment by LukasKalbertodt** [comment]
Even if you got tricked by the same problem twice, that simply means that it's very easy to make that mistake. And that in turn means that the user experience with Studio is bad in that regard. So let's keep this issue open until I've rewritten this part (also fixing #217). Then we can check this again.
