### ISSUE TITLE
Camera selection if no camera is present

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#457]
![Screenshot from 2020-03-04 18-09-41](https://user-images.githubusercontent.com/1008395/76018857-163edf00-5f21-11ea-82e8-896357514747.png)

The error makes sense since no camera was attached to this machine but it would be nice if users wouldn't even be presented with this choice if there is no camera. Is this possible?

**Comment by LukasKalbertodt** [comment]
Ehm, isn't this a dupe of #410?

**Comment by lkiesow** [comment]
Yes it is but I'm an old man now and do forget that I already complained about things. Closed.
