### ISSUE TITLE
Use Opencast Colors for the UI

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/opencast-studio#463]
If this is a Opencast Community project. I would prefer the Opencast colors instead of gray and black.

**Comment by LukasKalbertodt** [comment]
I personally don't care (apart from a complete color change being more work than no change), but I think @lkiesow prefers the grey-ish neutral color scheme.

**Comment by LukasKalbertodt** [comment]
#1069 implements a new design that was discussed with the community. Therefore, this discussion can be closed.
