### ISSUE TITLE
There should be a configuration setting in background or via get parameter.

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/opencast-studio#465]
If a user comes from an third system with opencast integration.
Id would be nice to set the configuration options for Opencast, while opening Opencast Studio.
So a user opens Opencast Studio out of a third system and Opencast Studio already set the Options.
Opencast Server url
Authentication
And the series where the recording should be uploaded.

**Comment by CGreweling** [comment]
If a user comes from an third system with opencast integration.
Id would be nice to set the configuration options for Opencast, while opening Opencast Studio.
So a user opens Opencast Studio out of a third system and Opencast Studio already set the Options.
Opencast Server url
Authentication
And the series where the recording should be uploaded.

**Comment by LukasKalbertodt** [comment]
Implemented. See the README for information on how to pass this information via GET parameters.
