### ISSUE TITLE
(Firefox) Streams seem to have a decoding issue

### ISSUE THREAD

**Issue by darolfes** [elan-ev/opencast-studio#5]

**Comment by luniki** [comment]
I need more details.

**Comment by darolfes** [comment]
The playback of videos in opencast recorded by opencast-studio on firefox often hangs completely. This most likely needs to be fixed in the opencast workflows. (Exact reason unknown, but it's probably not a problem of opencast-studio itself.)

**Comment by luniki** [comment]
I will close this issue for now. As soon as I find a reproducable problem on the OC Studio side, I will reopen it.
