### ISSUE TITLE
Drop the BETA logo

### ISSUE THREAD

**Issue by smarquard** [elan-ev/opencast-studio#503]
Moved from Opencast issues:

Opencast Studio is now part of 8.x and in production I'm certain in quite a few sites (we deployed it today), so it would be good to drop the BETA label in the banner, top-left.

It's now released, plus beta feels a little old-fashioned in the age of continuous updates.

**Comment by LukasKalbertodt** [comment]
We briefly discussed this internally and we agreed with you. It is time! See #505 :)
