### ISSUE TITLE
Handle long requests to info/me?

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/opencast-studio#533]
If Studio is not integrated (Opencast server is a different domain), it makes sense to handle timeouts of requests to info/me for example. The initial loading indicator is shown until the first info/me request succeeds, so that probably shouldn't take too long.

Regarding implementation, `Promise.race` is probably a good idea. [SO Link](https://stackoverflow.com/questions/46946380/fetch-api-request-timeout). The more difficult part is probably the UI and to communicate the timeout to the user effectively.

**Comment by lkiesow** [comment]
Why check `/info/me.json` at all at this point? Do you need any information from there?

**Comment by LukasKalbertodt** [comment]
No, not necessarily. But (a) it is currently very handy for debugging a deployment of studio (and LTI integration and what not) to immediately see if Studio is connected, and (b) it is pretty handy in the code and allows every component to easily get information about the current user. The latter was particularly interesting when we were still considering to bring back the "Go To Admin UI" button in the navigation for users that had the rights to see the admin UI.

But yes, precisely because it's not critically important in the beginning, I thought about having a short timeout.
