### ISSUE TITLE
Add always visible connection status indicator?

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/opencast-studio#534]
Maybe it would be useful to have an indicator (in the header?) that shows the connection to the Opencast server. This would likely be paired with a regular poll of info/me. Hovering or clicking that indicator would show a kind of drop-down element saying "you are connected" or "connection error: bla". Something like that.

**Comment by lkiesow** [comment]
I don't see the use-case for this. Particularly during and before the recording state I would even say that's confusing and distracting. Imagine you are doing a recording for half an hour and suddenly the indicator goes red, saying that you lost your connection. What should a user do? Cancel your recording? Check your connection? No, the correct answer would be to continue as if nothing happened. You can deal with the connection afterward. This is no live streaming. You can even do this offline. The single place where you actually need to know about your connection state is the upload dialog.

**Comment by LukasKalbertodt** [comment]
Yeah ok, fair point. Let's close this then.
