### ISSUE TITLE
Recording not created if not switching to tab

### ISSUE THREAD

**Issue by mtneug** [elan-ev/opencast-studio#537]
Probably a wontfix but wanted to report anyway.

Using Chrome and recording a tab only leads to an "empty recording" when the tab is never opened during the recording period (tested with 5s). Studio displays an error on the preview page.

**Comment by LukasKalbertodt** [comment]
Interesting! I wasn't aware of that behavior. Interestingly, this only happens with static websites. If you open a website where something "changes" (first one I found: https://css-tricks.com/almanac/properties/a/animation/), then a video is produced. Seems like Chrome just grabs all the frames its render engine produces and in the case of the static website, that is exactly one frame (tested with `ffprobe -select_streams v:0 -show_frames input.webm`). Recording audio doesn't change that behavior. 

Studio can't do anything about this, though. So as you correctly predicted, I'm gonna close this... as cantfix.
