### ISSUE TITLE
Record audio from Desktop

### ISSUE THREAD

**Issue by CarlCosinus** [elan-ev/opencast-studio#551]
Is such a feature planned in any way? i found this article [https://paul.kinlan.me/screen-recorderrecording-microphone-and-the-desktop-audio-at-the-same-time/](url) very interesting and i am trying to implement this functionality.

**Comment by LukasKalbertodt** [comment]
Hi there. Yes, the feature is planned. The main problem is the bad browser support right now: https://caniuse.com/#feat=mdn-api_mediadevices_getdisplaymedia_audio-capture-support

Only Chrome and Edge support it. And the support is only partial, as the footnote says:

> On Windows and Chrome OS the entire system audio can be captured, but on Linux and Mac only the audio of a tab can be captured.

Of course, Chrome and Edge on Windows already make up a significant part of users. So it might be worth looking into it even before browser support has improved.

---

> i am trying to implement this functionality.

So you are trying to implement it in Opencast Studio? Did I understand that correctly?

**Comment by CarlCosinus** [comment]
Yes, that is correct. I started a couple of days ago, but I had to do other things until today. I will keep on working on it from tomorrow on.

**Comment by CarlCosinus** [comment]
Whoops, guess I didnt read the link carefully enough. This explains why my it didnt record any audio from the desktop. Im working for Ssystems btw, the reason why im working on that matter.

**Comment by LukasKalbertodt** [comment]
Ah, very cool!

While this feature is welcome in general, I'm not quite sure if we want to include it into the community version already. That's precisely because of the confusing browser and OS support. Adding the feature might do more harm than good as it's not easy to communicate this to the user. Certainly interested in a PR. We will discuss this internally.

**Comment by kristofkeppens** [comment]
Would be interested in this feature as well, have some teachers asking for this.

**Comment by HomerJayAllTheWay** [comment]
Good evening everyone, any updates on this feature? Would love to record desktop audio in Chrome on my Mac or PC.

**Comment by lkiesow** [comment]
We planned to tackle this over the next 1-2 months to see if we can now make this work properly with current browsers.

**Comment by HomerJayAllTheWay** [comment]
> We planned to tackle this over the next 1-2 months to see if we can now make this work properly with current browsers.

Any updates on if/when you think this will make it into the product?
