### ISSUE TITLE
Wrong assumption: there could be multiple LTI roles

### ISSUE THREAD

**Issue by mtneug** [elan-ev/opencast-studio#567]
Using an LMS role provider, users could have multiple LTI roles attached. [Studio only uses the first value it finds](https://github.com/elan-ev/opencast-studio/blob/c21e03e15a3a69088f2b3a9af957ccbd31273d4d/src/opencast.js#L410-L416), which is not necessarily the correct LTI course id. I propose to add a configuration field for setting the correct `ltiCourseId`. The LMS could then set the correct id when redirecting users the Studio.

**Comment by lkiesow** [comment]
You found an extremely ugly hack in Studio but LTI does provide all the information you want so that you don't need to extract this information from any role. Take a look at #511 for details.

**Comment by mtneug** [comment]
That would indeed be the best solution.
