### ISSUE TITLE
Allow setting a min fps

### ISSUE THREAD

**Issue by mtneug** [elan-ev/opencast-studio#568]
To prevent [results like these](https://video.stackexchange.com/questions/29865/ffmpeg-variable-framerate-with-min-and-max), I propose a new option for setting a minimal fps analogous to `display.maxFps` and `camera.maxFps`.

Before I sit down implementing this, do you know if the browser will actually follow the constraint? [Acording to MDN](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/frameRate) most browser should support the `frameRate` constraint, but I'm not sure if this is actually the case for a minimum.

Maybe it would even be helpful to set a reasonable default (there should at least be a frame every second, right?).

**Comment by LukasKalbertodt** [comment]
I quickly looked at it and it seems we cannot do anything about this. Setting `frameRate: { min: 30 }` in the constraints leads to `getDisplayMedia` immediately rejecting -- the user is not even prompted to choose a window (tested with Chrome and Firefox). Setting `frameRate: { ideal: 30 }` does result in a valid video stream, but it does not seem to fix the issue you describe here: capturing a tab that doesn't contain any changing things still results in frames with a super long duration.

I don't think we can do anything about that, really. It's rather a browser bug/behavior that would need to get fixed. So I'll close this for now. If you find a way for Studio to fix this, just ping me and we can reopen this issue.
