### ISSUE TITLE
Add Seriestitle Selection and default Contributor

### ISSUE THREAD

**Issue by CarlCosinus** [elan-ev/opencast-studio#569]
It would be nice to have a Dropdown-Selection of available Series-Titles ( Series where you have write access) as well as another field for a description. In addition setting the Contributor as username per default would be a nice feature. 

![image](https://user-images.githubusercontent.com/60257804/79367804-bb9c9800-7f4e-11ea-9fcc-4e93cfd397a7.png)

**Comment by LukasKalbertodt** [comment]
I split this issue into #776, #777 and #778 to better discuss the three independent feature requests in isolation.
