### ISSUE TITLE
[Feature Request] Use the possibility to recode the browser window audio output 

### ISSUE THREAD

**Issue by MBcom** [elan-ev/opencast-studio#576]
# Summary
In https://screenapp.io/#/ there is the possibility to record the browser window audio output.
This would be an improvement, because then there is no need to change the browser settings for recording computer audio output.

**Comment by LukasKalbertodt** [comment]
Hi there! If I understand you correctly, then we already have an issue for that: https://github.com/elan-ev/opencast-studio/issues/551
Is that in fact what you were requesting? Then I'd close this as duplicate.

**Comment by LukasKalbertodt** [comment]
Closing as dupe now. If you meant something else, just comment here and we can reopen.
