### ISSUE TITLE
AbortError: The fetching process for the media resource was aborted by the user agent at the user's request.

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/opencast-studio#581]
We observed this issue via Sentry ([link](https://sentry.virtuos.uos.de/virtuos/opencast-studio/issues/115/), for those with access), but I unfortunately couldn't reproduce it locally. The following error occurs:

```
AbortError: The fetching process for the media resource was aborted by the user agent at the user's request.
```

It only happens in Firefox, but on multiple operating systems. It seems to happen immediately after stopping the recording (for non Germans: "Aufzeichnung beenden" is "Stop recording"):

![Screenshot from 2020-04-23 12-20-23](https://user-images.githubusercontent.com/7419664/80088486-ded1d380-855c-11ea-9786-235b64158590.png)

So the issue is with the review page not being able to load the video file, it seems. The `<video>` element's `src` is set to an internal blob URL. No idea what could cause this.

If anyone can reproduce this issue, I'd be glad about any information!

**Comment by LukasKalbertodt** [comment]
Searching for this error kind in the Firefox source does not lead to many results: https://searchfox.org/mozilla-central/search?q=NS_ERROR_DOM_MEDIA_ABORT_ERR&redirect=false

So it would be possible to check for all of those couple of situations.

**Comment by lynnporu** [comment]
Have no idea what your project does, but just found this page trying to solve the same issue. This error may appear in asynchronous threads, when there's high risk of race condition. In my case I was calling Audio.play() earlier then Audio.load(), i.e. file was not loaded at the moment I tried to play it. It seems that other browsers prevents situations like that in some way. Maybe it can help you. Have a nice day :)

**Comment by LukasKalbertodt** [comment]
@lynnporu Thank you very much! :heart:

**Comment by subnut** [comment]
@lynnporu Thank you very much. I had a video element, that started playing fine when `video.load()` was called the first time. (i.e.`Promise: { state: <fullfilled> }`). But once I did `video.pause()`, then `video.play()` _just wouldn't work!_. Running `video.pause()` would cause the error shown above, as many times as `video.play()` was called before `video.pause()`

I thing was, I simply had to call `video.load()` before `video.play()`!! Thank you, again!

**Comment by AleksandrHovhannisyan** [comment]
We fixed this problem by registering a `loadeddata` event listener on the video element that we were trying to play, then `load()`ing the video, and finally `play()`ing it inside the event handler:

```js
const playVideo = (video) => {
  video.addEventListener('loadeddata', () => {
    video.play();
  });
  video.load();
}
```

(Just remember to remove the event listener when appropriate. Not shown here for brevity.)

If you're playing videos on hover/focus and resetting them on mouseleave/blur, you may need to flip a boolean flag to true/false to act as a locking mechanism. Something like this:

```js
let shouldPlayVideo;

const playVideo = (video) => {
  shouldPlayVideo = true;
  video.addEventListener('loadeddata', () => {
    // This may have flipped to false if resetVideo was called before loadeddata fired
    if (shouldPlayVideo) {
      video.play();
    }
  });
  video.load();
}

const resetVideo = (video) => {
  shouldPlayVideo = false;
  video.load();
}
```

**Comment by SabriGharsalli** [comment]
in some cases the video is being loaded and that s why that error  exists so in order to solve it u need to add a check on the availability of the video then play it
`this.videoRef.current.addEventListener('canplay', () => {
          this.videoRef.current.play();
        });`

**Comment by LukasKalbertodt** [comment]
I don't think Opencast Studio has this problem anymore. Since the issue was opened, most code has been refactored and we haven't gotten any report about something like this. I don't think keeping this issue open makes any sense.

It is kind of amusing that this issue appeared high in the google results for this error. Hopefully this helped in some way. But yes, for this project it makes no sense to keep it open.
