### ISSUE TITLE
Show Authentification Status in the Upload UI 

### ISSUE THREAD

**Issue by rrolf** [elan-ev/opencast-studio#591]
Several users fail in the upload or it takes them quite a while to record and upload their recording. 

At least at our institution we use the LTI Auth from the LMS and this runs out after some hours. 

Users do not know ist they are still authenticated, if they (re-)try an upload after a while. So it would be good to have an indicator in the upload UI of Studio if the user is still authenticated and a text box where the institution would give hints on how to deal with this problem.

**Comment by lkiesow** [comment]
- We shouldn't distinguish between LTI authenticaton and other authentication mechanisms
- We probably could keep sessions alive by requesting data from Opencast in regular intervals

**Comment by LukasKalbertodt** [comment]
I agree with Lars. Regularly polling info/me was already considered some time ago. Should be fairly easy to implement. Will do so when also fixing this very related issue: https://github.com/elan-ev/opencast-studio/issues/559
