### ISSUE TITLE
Return URL

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#593]
In certain scenarios, it would be nice to be able to pass a return URL to studio to which Studio will (optionally) lead you after you finished the upload/download as an alternative to “new recording”

**Comment by mtneug** [comment]
When coming from Moodle, Studio will be opened in a new window/tab. Maybe, in this case, a button for closing the window/tab would be more appropriate (then again you can do that with the usual browser features).

**Comment by LukasKalbertodt** [comment]
JS is not allowed to close windows that weren't opened by scripts. Moodle, Studip and other LMS usually just have a simple `<a target="_blank"` link, so: Studio cannot close itself. See [here for more information](https://stackoverflow.com/a/19768082/2408867).

In those cases, I see two possibilities:

- Show a message like "To return to {LMS name}, please close the current browser tab". This might confuse a few users who don't understand what a browser tab is...
- Just link to the "return URL". Users can simply click the button, but then they have two tabs with the same LMS page loaded.

Neither sounds like a great solution...
