### ISSUE TITLE
Change "Download" to "Save"

### ISSUE THREAD

**Issue by ypatios** [elan-ev/opencast-studio#598]
After a recording has been finished, the user can choose to upload it to Opencast and/or "Download" it locally.
<img width="346" alt="image" src="https://user-images.githubusercontent.com/21248330/80580516-ee916200-8a0b-11ea-822f-e74ce3fee2a7.png">

I find the term "Download" confusing, as the recording lies already on the user's computer. Therefore the term should be changed to "Save", for example.

**Comment by LukasKalbertodt** [comment]
> I find the term "Download" confusing, as the recording lies already on the user's computer.

Absolutely, that is strange. I think we chose "Download" as it would be familiar to most users, especially inexperienced ones. And those users might also not care about the technical specifics. But I guess "Save" is a good alternative and I think I'm fine with it! I will ask a few other people what they think. Thanks for the suggestions!

**Comment by ypatios** [comment]
my pleasure!
wrote already in the opencast mailinglist:
https://groups.google.com/a/opencast.org/d/msg/users/f0G_2GSytS0/Y_GHJj2NDwAJ

**Comment by LukasKalbertodt** [comment]
Some people brought up the problem of users thinking of "save" as in ... MS Word for example. There, users basically always save if they changed anything. So this new name might confuse more users than are previously confused by the "Download" that just copies the file on your local disk. Again, our target users (non technically-versed) probably don't care/know about the fact that the video file is already on their device.

**Comment by ypatios** [comment]
what about "Save as..." or Save recording as..."?

**Comment by LukasKalbertodt** [comment]
I don't think that's better as users would associate that with "the same as 'save' but I can chose the file name and location". Which is not even true here.

I also thought of "Save to disk" but that has the same problem as "Download" I assume.

**Comment by ypatios** [comment]
Yes, it's not easy to be technically correct and also cover all corner cases of users misinterpreting things.
But since we have the term "Discard" in "Discard and record again", we should find an antonym to this, right?
here's what I find online:
"keep", "save", "reserve", "retain" ...
Maybe "keep" is a good option?

**Comment by lkiesow** [comment]
I think Download makes the most sense in browser terms. Remember, you are in a browser and not in a local application. I also don't think its technically wrong since it's downloading (transferring)  it from the browser's cache to a location on the user's disk they chose or their browser chose for them.

This is also the terminology other common web applications (e.g. Google Docs) are using regardless of being in online or offline mode (meaning the files could be tranbsferred from the browser cache as well).

In general, I think it's an extremely technical complaint and you need to know a lot about how the internals of Studio work why “Save” _could_ be better than „“Download” and I really don't think it's something common users will understand. They will rather be confused by what the button does.

**Comment by ypatios** [comment]
To use the term "Download" for transferring from one place of the hard-disk to another sounds much more technical to me (but it is correct, of course). The common internet user understands "Download" as an action that involves the transfer of a file from the internet to their computer (at least this is my impression, as a non-too-technical user ;))
Anyway, we had this problem already with test users asking "why download" since we have promoted that this tool (as also described in the "about" section) makes recordings only locally.
I'm afraid that, especially nowadays with users being much more aware regarding their personal data, it is crucial to make it clear that the recordings are only local and never find their way to a server (unless of course the user chooses to "upload" them).

**Comment by LukasKalbertodt** [comment]
We haven't come up with a good alternative to "download" ("save" and others have their own problems) and the problem with "download" is rather minor. So I'm will close this issue for now.
