### ISSUE TITLE
partial-ingest wf tag operation +archive results in ", archive" tag

### ISSUE THREAD

**Issue by ypatios** [elan-ev/opencast-studio#599]
When uploading a recording from Opencast Studio to Opencast, in the partial-ingest workflow (which is included in the studio-upload workflow) the tag operation with config "+archive" results in the media being tagged with ", archive".
<img width="454" alt="image" src="https://user-images.githubusercontent.com/21248330/80733878-968f5400-8b0e-11ea-98b2-c2e102612a45.png">

This implies that the original file (from Opencast Studio) has a non-empty (but invisible) tag list(?)
It is easy to miss this, as in the following operations the media get retagged again.

The issue can be reproduced also on stable.opencast.org

**Comment by LukasKalbertodt** [comment]
This issue should rather be reported on the opencast repository as this is an issue with the workflow and the workflow definition lives in said repo. It would be great if you could open the issue there :)

**Comment by lkiesow** [comment]
This is a known Opencast bug. If I remember correctly, an empty tag might be added in some cases. Not sure if it has already been fixed. But it's certainly no Studio bug.

**Comment by ypatios** [comment]
I see. I was convinced that it was this function worked OK on Opencast. Sorry for the noise.

**Comment by LukasKalbertodt** [comment]
No problem at all! I much prefer a misplaced bug report over a bug that isn't reported ;-)
