### ISSUE TITLE
Connect Crowdin

### ISSUE THREAD

**Issue by darolfes** [elan-ev/opencast-studio#6]

**Comment by lkiesow** [comment]
- [ ] Use JSON for translation files
- [ ] Use a platform like Crowdin
- [ ] Complete translations

**Comment by luniki** [comment]
Welche Sprachen sollen unterstützt werden?

**Comment by luniki** [comment]
Connected the problem to crowdin:

https://elan-ev.crowdin.com/opencast-studio

**Comment by lkiesow** [comment]
We can probably start with [the languages Opencast is properly translated into](https://crowdin.com/project/opencast-community). Opencast usually adds languages on demand and ships them if they have a proper translation (≥90% – …actually a bit more complicated than that but that's near enough)
