### ISSUE TITLE
Automate Deployment

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#63]
Automatically build this tool and deploy it to the `gh-pages` branch once issue #56 has been resolved.

**Comment by luniki** [comment]
Deployment is now done on invoking "npm run deploy". Unfortunately I have to set the custom domain name everytime I run this :-1: 

Will have to investigate this…

**Comment by lkiesow** [comment]
@luniki, `npm run deploy` is all nice and well but does not fix this issue since it's still not automated. I've created pull request #139 which will automatically push updates to the `react` branch to `gh-pages`. It's using a deployment key specific to this repository.
