### ISSUE TITLE
Ensure screen is always on during a studio recording

### ISSUE THREAD

**Issue by NgoniChoga** [elan-ev/opencast-studio#631]
We've noticed that the screen can go to sleep during an opencast studio recording which results in the recording stopping (frozen screen) and subsequently a double recording after re-recording. Steps to reproduce:

1. Start an OC studio recording.
2. Wait for screen to go to sleep.
3. Wake up the screen. When you wake up the screen, you will notice that the recording will have paused.
4. Go back to the start page to start a new recording by clicking the top left logo.
5. Start a new recording.
6. Stop recording.
7. On the last screen before submitting, you will see the old erroneously stopped recording as well as the new recording.
8. If you submit, the video will have 2 presentation/source recordings (for example) and therefore fails.

**Comment by LukasKalbertodt** [comment]
Interesting! Did not consider that at all. Will see what we can do about it.

**Comment by LukasKalbertodt** [comment]
Ok, let's close this issue then. Reporting this as browser bugs seems like a good idea.
