### ISSUE TITLE
`opencast.serverUrl` can't be the empty string

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/opencast-studio#689]
According to [the docs](https://github.com/elan-ev/opencast-studio/blob/master/CONFIGURATION.md),

```
[opencast]
serverUrl = ""
```

Should basically be equivalent to

```
[opencast]
serverUrl = "/"
```

However, while the latter works for me, the former doesn't. The Opencast connection is reported to be `"unconfigured"` in the DevTools console.

**Comment by lkiesow** [comment]
Is an empty string really a valid URL?
I don't think it is, is it?

**Comment by JulianKniephoff** [comment]
Maybe not, but I rather took the docs to suggest that `""` would be treated specially, irregardless of that.
