### ISSUE TITLE
Default Windows app cannot playback downloaded .webm file

### ISSUE THREAD

**Issue by peculiarPrince** [elan-ev/opencast-studio#694]
The “Movies & TV” app (Microsoft’s default video player in Windows 10) as well as Windows Media Player are unable to play videos without audio downloaded from Edge in the .webm format. If the video includes audio, the sound will be played back without picture.

**Comment by LukasKalbertodt** [comment]
That's unfortunate, but we can't really do anything about this :/ 
See https://github.com/elan-ev/opencast-studio/issues/202 for a discussion on changing the video format. Studio just has to take what the browser offers, basically.
