### ISSUE TITLE
Vertical Bar through Shared Screen view

### ISSUE THREAD

**Issue by peculiarPrince** [elan-ev/opencast-studio#695]
Black bar vertically down the Shared Screen view in Opencast Studio (although not in source). 
![image](https://user-images.githubusercontent.com/38320410/91452976-82baeb00-e87f-11ea-88c2-21849badba09.png)

Possibly due to having had the source in multi-window view during selection and then making it full screen before recording. Was not able to reproduce.

**Comment by LukasKalbertodt** [comment]
This is very likely a bug in the browser's desktop capturing feature, not Studio. Closing.
