### ISSUE TITLE
Opencast Studio Logo - is it a button?

### ISSUE THREAD

**Issue by peculiarPrince** [elan-ev/opencast-studio#697]
If it is, this could be made a lot more obvious. All other buttons have clear borders and/or colors. When clicked, it has the same function as the "Recording" button on the upper right hand side.

**Comment by cgruber-uos** [comment]
Currently clicking on the OC logo is the same as clicking on "Recording" (also in the header right side). 

But I would expect that clicking on the main website logo leads me to the homepage, means for Studio to the start page for a new recording / the first step of a recording even if I have selected cam and screen already, so it would be also a kind of emergency button in case I don't know where I am or shortcart for starting over.

**Comment by LukasKalbertodt** [comment]
This changed with #1069. It is no longer a button and does nothing when clicked.
