### ISSUE TITLE
Downloading media is "from: blob: "

### ISSUE THREAD

**Issue by peculiarPrince** [elan-ev/opencast-studio#698]
![image](https://user-images.githubusercontent.com/38320410/91456961-25756880-e884-11ea-96c6-f030e8aa499a.png)

**Comment by LukasKalbertodt** [comment]
This is a bug in Firefox and apparently, Studio can't do anything about it :/ 

See:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1053327
- https://stackoverflow.com/questions/45792525/firefox-set-blob-download-source
