### ISSUE TITLE
Wasted white space: change dimensions of recording thumbnails

### ISSUE THREAD

**Issue by peculiarPrince** [elan-ev/opencast-studio#700]
While the browser is maximized in the 14-inch screen, the preview thumbnail of both display and camera recordings with their respective "download" buttons could conceivably fit next to each other, but are instead stacked so that the user has to scroll down to download the next video.

**Comment by LukasKalbertodt** [comment]
Do you have a screenshot of that? That would probably explain the problem best :)

**Comment by peculiarPrince** [comment]
![image](https://user-images.githubusercontent.com/38320410/91840632-4b6a8680-ec51-11ea-89ef-08a47e1cac53.png)

**Comment by LukasKalbertodt** [comment]
The second thumbnail will be right of the first one, *if* the horizontal screen space allows for it. Your case is kind of unfortunate as the screen size is almost but not quite large enough for that. But there is not really a good and easy solution that works for all screen sizes :/
