### ISSUE TITLE
No need to scroll down to start a new recording

### ISSUE THREAD

**Issue by peculiarPrince** [elan-ev/opencast-studio#701]
The entire recording process fits onto one screen (no scrolling necessary) until after a successful upload, when the “Start a new recording” button is present but not immediately visible (scrolling necessary in 14-inch screen). There is a lot of white space, with no indication of a restart button until the user realizes they must for the first time scroll down.

Change the dimensions of the area to always fit onto the full screen, or make it more obvious that the user needs to scroll down to find the next button.

**Comment by LukasKalbertodt** [comment]
Could you take a screenshot of that?

**Comment by peculiarPrince** [comment]
Note: This is not relevant when the message about cutting is not displayed (for recordings with one source only).
Without a cut:
![image](https://user-images.githubusercontent.com/38320410/91840892-b61bc200-ec51-11ea-9b05-f69f69bbbf86.png)

With a cut:
![image](https://user-images.githubusercontent.com/38320410/91841051-f9763080-ec51-11ea-880d-c70c443d89a1.png)

**Comment by LukasKalbertodt** [comment]
Mhhh, this is somewhat intended. I mean, for certain screen sizes, the layout can indeed be unfortunate. I reduced the empty space between the bottom buttons and the main content in 3cbc918. Other than that, I think it can stay as is.
