### ISSUE TITLE
Auto-rotate froze review/edit of recording

### ISSUE THREAD

**Issue by peculiarPrince** [elan-ev/opencast-studio#704]
Similar to Issue #703 :
Once in preview mode, I flipped the tablet sideways (to auto-rotate to landscape view), and could no longer click "Play" or edit in any way. 
Tapped Next to see if downloading was possible (it was), flipped tablet back up (to portrait view), hit Back, and the loading circle icon appeared without ever showing the video again.

**Comment by LukasGermscheid** [comment]
I couldn't reproduce the problem. I tried it with two tablets, the ipad pro 21 and with sony xperia android. I started the recording in both modes and flipped the tablet in the preview. The player/editor was still functional. I used https://studio.opencast.org/ to test the issue.

**Comment by lkiesow** [comment]
Thanks for testing this again. Browsers have become a lot better when it comes to video in the last years. Let's just assume that the problem is fixed. We can always reopen this if the problem pops up again.
