### ISSUE TITLE
Confusing pointer arrow in upload dialog

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#71]
Several non-links show a pointer arrow on mouseover but have no action configured. One would expect that for links only.

<img src="https://user-images.githubusercontent.com/1008395/66753043-2a5f4280-ee93-11e9-8b9f-7fa638f5637f.jpg" width="150"
 /> <img src="https://user-images.githubusercontent.com/1008395/66753044-2af7d900-ee93-11e9-8b11-e3fdabd743d0.jpg" width="150" />

**Comment by sivagurucse** [comment]
https://github.com/elan-ev/opencast-studio/pull/101
