### ISSUE TITLE
About page: Text needs padding

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#72]
The text on the About page is extremely close to the border, making it somewhat hard to read. Just adding a small border should already help.

<img src="https://user-images.githubusercontent.com/1008395/66782847-eee66780-eed6-11e9-8cd3-95c53a2fbf8d.jpg" width="400"/>

**Comment by callmeanto** [comment]
I'll work on this! :)

**Comment by lkiesow** [comment]
That was quick! Thanks for tackling this.

**Comment by callmeanto** [comment]
Done! just added a media query for small screens and added a css rule for **article** selector
