### ISSUE TITLE
Rendering the presenter pip (picture-in-picture) instead of on the left side

### ISSUE THREAD

**Issue by zenny** [elan-ev/opencast-studio#722]
Hi,

Just came across the opencast-studio. An excellent capture-agent (CA). Excellent job. :+1: 

However, how can one render the video in pip mode instead of by side-by-side to ingest into the opencast-server or any other LMS?

Is there an option for different video layouts?

Cheers, and stay safe,
/z

**Comment by lkiesow** [comment]
If you ingest your video to Opencast, you can create a picture in picture composite video as part of your workflow using the [composite workflow operation](https://docs.opencast.org/r/8.x/admin/#workflowoperationhandlers/composite-woh/).

But depending on which Opencast player you are using, you can also natively set that in the player with no need to render that to a fixed position:

![Screenshot from 2020-09-13 21-15-21](https://user-images.githubusercontent.com/1008395/93026469-7320fd80-f606-11ea-8d96-79384773a206.png)

**Comment by zenny** [comment]
> If you ingest your video to Opencast, you can create a picture in picture composite video as part of your workflow using the [composite workflow operation](https://docs.opencast.org/r/8.x/admin/#workflowoperationhandlers/composite-woh/).
> 
> But depending on which Opencast player you are using, you can also natively set that in the player with no need to render that to a fixed position:
> 
> ![Screenshot from 2020-09-13 21-15-21](https://user-images.githubusercontent.com/1008395/93026469-7320fd80-f606-11ea-8d96-79384773a206.png)

@lkiesow Thanks for extremely useful reply. And thanks to the link to `composite workflow operation`. Cheers, and stay safe.
