### ISSUE TITLE
Preview video is cropped

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#73]
The preview video is cropped to a fixed aspect ratio, potentially hiding most of the actual video which is recorded. This makes it almost impossible to properly use Studio in some circumstances. This is especially true for mobile recordings in portrait mode.

Here is an axample for a smartphone recording in portrait mode. First the preview, then the – totally different – result:

<img src="https://user-images.githubusercontent.com/1008395/66783028-5c929380-eed7-11e9-9b2f-fe917b88ef01.jpg" width="250"
/> → <img src="https://user-images.githubusercontent.com/1008395/66783029-5d2b2a00-eed7-11e9-8419-ea7d8b2c3530.jpg" width="250"/>

**Comment by LukasKalbertodt** [comment]
@luniki You self assigned this three weeks ago. Did you already start working on this? If not, I'd like to try fixing this issue.

**Comment by luniki** [comment]
Go ahead :-)
