### ISSUE TITLE
Weird overlay over preview videos

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#733]
There is a weird cutout in all preview videos in (at least) Firefox on desktop. The developer tools reveal that it seems to contain the resolution, although you cannot see that as user

![Screenshot from 2020-10-05 18-12-15](https://user-images.githubusercontent.com/1008395/95104998-d3531d00-0736-11eb-933a-997e4664fefa.png)

**Comment by LukasKalbertodt** [comment]
Unfortunately, I cannot reproduce :/ I tried this with webcam/screen, screen with different aspect ratios, different browser zoom levels, chrome and firefox. Can you tell me how to reproduce?

**Comment by lkiesow** [comment]
Can't reproduce this any longer. Closing.
