### ISSUE TITLE
UX Improvement: Infinite screens

### ISSUE THREAD

**Issue by NgoniChoga** [elan-ev/opencast-studio#752]
When you start Opencast recordings (display recording) it shows this "inception moment" of infinite screens. Some users find this very confusing. Please see attached image: 
![image-2020-10-21-19-36-39-622](https://user-images.githubusercontent.com/18629266/99666820-2e856880-2a74-11eb-9eb0-785c127c2a17.png)

**Comment by LukasKalbertodt** [comment]
Hi there! Do you have any suggestion how to improve this? Because I currently don't really see how we would be able to improve this: this is simply a consequence of seeing a preview video.

**Comment by NgoniChoga** [comment]
Hi, yes, I understand that this is a consequence of seeing a preview video, however it appears to really mess with users for some reason. A potential solution (I am unsure about the difficulty level or amount of time that would need to be invested): snap a picture of the current display screen and use that as a preview image instead of having a preview video? Let me know if this makes sense as a suggestion.

**Comment by LukasKalbertodt** [comment]
But then the preview would be not really helpful anymore. Most users would expect the review to auto-update and not only show a single frame from when the screen was shared. 

Also note that users can chose not to record the full screen, but single windows or tabs. In those cases, this "infinite screens" effect does not occur. But we (as in: the Studio code) cannot distinguish between those cases. 

As far as I can see, the only way to properly tackle this "confusion" of users is by providing them with guides or tutorial videos which mention that effect.

**Comment by LukasKalbertodt** [comment]
As you seem to agree with my last comment, I will close this issue. If anyone has any better idea, please let me know.

**Comment by samleepan** [comment]
Hi @LukasKalbertodt  @NgoniChoga  Other screencasting software have a count down screen scree/n e.g. 3,2,1 so they can navigate to the appropriate application/screen before it start's recording. Would this be a possibility?

**Comment by LukasKalbertodt** [comment]
@samleepan if I'm understanding you correctly, this is not related to the infinite screen issue, right? Regarding countdown, we discussed this in https://github.com/elan-ev/opencast-studio/issues/201. The gist is: since Studio can now cut the beginning end end of the video, we felt that a countdown is not necessary anymore.

**Comment by samleepan** [comment]
@LukasKalbertodt  Thanks - that makes sense, and definitely helps. We have a team chat tomorrow and will discuss if we have any other suggestions for improvement.
