### ISSUE TITLE
Visual feedback on success

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#76]
Right now, the success dialog reminds me of an error dialog more than anything else. A few suggestions for improving the visual impact for this element include:

- [ ] remove the `×` for closing the dialog
- [ ] don't use a colon at the end of a heading
- [ ] use something like a [green checkbox with a checkmark (☑)](https://fontawesome.com/icons/check-square?style=solid) to visually represent success
- [ ] Maybe be simple and just shout „Upload succeeded“. People know that it is a notice.

What are we talking about:

<img src="https://user-images.githubusercontent.com/1008395/66784102-c6ac3800-eed9-11e9-8538-840d38fd5048.jpg" width="300"/>

**Comment by CharaeKeow** [comment]
Do you think the dialog should disappear after a few seconds or the user need to close it? Also the background shouldn't need to be darker when the dialog appears imo.

**Comment by lkiesow** [comment]
I would probably not automatically close it. Depending on your recording length, its size and your internet connection, an upload might take quite a while and you may choose to have the page in the background. If you come back a while later, it would still be nice to get visual feedback. 

However, we cloud close the dialog if you click anywhere on the page.

Regarding the semi-transparent, dark background, I would leave it like this for now since it is consistent with all other dialogs in Studio right now.
