### ISSUE TITLE
Set `dcterms:contributor` to the user's username

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/opencast-studio#778]
Is that what the field is used for? Should it be the username? If so, we can always set it.

**Comment by lkiesow** [comment]
`contributor` and `creator` should have the same form but have different meanings. You could always argue that a creator is also a contributor. But I find adding the user twice odd. And adding the username instead of the real name would be very uncommon.

**Comment by lkiesow** [comment]
- Creator
    - https://www.dublincore.org/specifications/dublin-core/dcmi-terms/elements11/creator/
    - __Definition:__ An entity primarily responsible for making the resource.
    - __Comment:__ Examples of a Creator include a person, an organization, or a  service. Typically, the name of a Creator should be used to indicate the  entity.
- Contributor
    - https://www.dublincore.org/specifications/dublin-core/dcmi-terms/elements11/contributor/
    - __Definition:__ An entity responsible for making contributions to the resource.
    - __Comment:__ The guidelines for using names of persons or organizations as  creators also apply to contributors.  Typically, the name of a  Contributor should be used to indicate the entity.

**Comment by LukasKalbertodt** [comment]
Mh okay, so we will just not do this? I'd be fine with just closing this issue.

**Comment by lkiesow** [comment]
What was your intention in proposing this?

**Comment by LukasKalbertodt** [comment]
I'm not quite sure anymore :D I think I just thought "maybe this field is intended to hold the username". But yeah, it is not, so let's close this.
