### ISSUE TITLE
Regular font weight

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#78]
The font-weight of the regular font is weird since the letters are thicker than the actual headings for the sections. I would expect them to have a regular, non-modified weight.

<img src="https://user-images.githubusercontent.com/1008395/66784501-f3ad1a80-eeda-11e9-83a1-0f2c97a1581e.png" width="300"/>

**Comment by LukasKalbertodt** [comment]
Can we close this issue in favor of a new, more general "polish design" issue? I feel like if we would create an issue for each minor design problem like that, I could instantly create tens of issues.

**Comment by LukasKalbertodt** [comment]
Irrelevant/solved since #1069
