### ISSUE TITLE
Half hidden, blue description texts behind media preview

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#79]
For example, when recording an ultrawide video (see below) a blue “desktops” appears half-hidden behind the media preview images. This explanation should either appear below the preview image or (preferably?) be removed entirely.

<img src="https://user-images.githubusercontent.com/1008395/66785177-c497a880-eedc-11e9-8979-56001b012829.png" width="300"/>

**Comment by luniki** [comment]
This is a leftover from the previous iteration and should be removed ASAP.
