### ISSUE TITLE
Position of recording button inconsistent on iOS

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#81]
Unlike all other systems, on iOS, the recording button is overlaying the recording preview on iOS. Assuming space would actually be used by valid, functional previews, this wouldn't necessarily be a bad thing since it makes easily accessible (see image below), but it should match the other systems.

<img src="https://user-images.githubusercontent.com/1008395/66785845-bb0f4000-eede-11e9-98b2-8dcfe1978819.jpg" width="300"/>

**Comment by luniki** [comment]
Should be done by now.
