### ISSUE TITLE
Update theme-ui to 0.6

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/opencast-studio#812]
We are on 0.3.2, but luckily 0.4 and 0.5 were only alpha releases and it should be fine to go directly to 0.6. See https://github.com/system-ui/theme-ui/blob/develop/CHANGELOG.md

**Comment by naweidner** [comment]
Theme-ui updated to 0.14.5 with commit [435cac1](https://github.com/naweidner/opencast-studio/commit/435cac1460a580668cf00e50625a4aa99db38b1e)
