### ISSUE TITLE
Wrong resolution in dual monitor setup

### ISSUE THREAD

**Issue by mwageringel** [elan-ev/opencast-studio#817]
With two monitors that have different resolutions, the resolution for screen capturing is determined by the resolution of the screen containing the browser window, not the resolution of the screen that is captured.

**Example**:

- Primary monitor resolution: 1200×1920 (width × height, portrait mode) containing the browser window.
- Secondary monitor resolution: 1920×1200 (landscape).

- Expected resolution when capturing the second screen: 1920×1200 (w×h).

- Actual resolution (using the `auto` option): 1200×750.

- Workaround: move the browser window to the screen that is captured.

Presumably, the video resolution is scaled down to a width of 1200 because that is the width of the primary monitor. Similar problems occur when selecting the predefined quality options like 720 (which would result in a resolution of 720×450 instead of 1152×720), when capturing an application window, or when using two monitors in landscape orientation that have different resolutions. Tested with version 2020-06-25 using Chrome on Linux.

**Comment by LukasKalbertodt** [comment]
Hi and thank you for this bug report. My guess is that this is a bug in the browser, and not in Studio. Could you test if you get the same behavior with this demo page? https://www.webrtc-experiment.com/getDisplayMedia/
You can see the width and height of the stream below the preview.

**Comment by mwageringel** [comment]
Thanks for the quick response. Indeed, this seems to depend on the browser. With Firefox, the problem does not exist, but I have replicated the issue with Chrome and Brave (which is Chromium-based) on Linux and macos.

With the setup described in the original post, this is the output of the test page using Chrome when sharing the entire second screen (which should have height 1200 and width 1920 instead):

```
settings:

{
	"aspectRatio": 0.625,
	"deviceId": "screen:369:0",
	"frameRate": 30,
	"height": 1920,
	"resizeMode": "crop-and-scale",
	"width": 1200,
	"cursor": "always",
	"displaySurface": "monitor",
	"logicalSurface": true
}

capabilities:

{
	"aspectRatio": {
		"max": 1200,
		"min": 0.0005208333333333333
	},
	"deviceId": "screen:369:0",
	"facingMode": [],
	"frameRate": {
		"max": 30,
		"min": 0
	},
	"height": {
		"max": 1920,
		"min": 1
	},
	"resizeMode": [
		"none",
		"crop-and-scale"
	],
	"width": {
		"max": 1200,
		"min": 1
	}
}
```

The same happens when sharing just a smaller application window on the second screen.

With Firefox, the test page gives an error.

(I have also noticed a different problem with just Firefox on Linux: it is not possible to share the individual monitors, but just a very large combined version that shows the two screens side-by-side.)

**Comment by lkiesow** [comment]
> I have also noticed a different problem with just Firefox on Linux: it is not possible to share the individual monitors, but just a very large combined version that shows the two screens side-by-side.

That's a limitation of Firefox

**Comment by LukasKalbertodt** [comment]
That's some strange Chrome behavior. I guess Studio can't really fix anything in that regard. So the best course of action is for you to create a chrome bug report and us closing this issue here, right?

**Comment by mwageringel** [comment]
Yes, now that I understand this better I agree this is difficult to circumvent, so I am closing this. I have reported the issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=1199887#c1
