### ISSUE TITLE
Configuration: Weird selection on iOS

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#82]
Opening the configuration dialog on iOS,I ended up with a weird pre-selection on the input fields:

<img src="https://user-images.githubusercontent.com/1008395/66786088-7f28aa80-eedf-11e9-890a-1271fd6c1e92.jpg" width="300"/>

**Comment by luniki** [comment]
Is this reliably reproducable?

**Comment by LukasKalbertodt** [comment]
I can't reproduce that with the new configuration page introduced in #182. Closing for now.
