### ISSUE TITLE
Screen recording non-functional on mobile devices

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#83]
While it may be impossible to add screen recording to mobile devices for technical reasons, we must not offer this option in such a case. Right now, that's the first option users are presented with and clicking this makes the tool look like it's just completely broken.

<img src="https://user-images.githubusercontent.com/1008395/66786400-7ab0c180-eee0-11e9-880d-dcb561858e4d.gif" width="300"/>

**Comment by luniki** [comment]
As this is technically impossible I will just hide the unusable option.

**Comment by luniki** [comment]
It is easy to filter unsupported sources. It is not easy to create a layout supporting 0-2 sources.

**Comment by LukasKalbertodt** [comment]
Currently we use these tests to determine whether the user's browser supports screen recording:

https://github.com/elan-ev/opencast-studio/blob/d52b01eb3e496d1092ff1869ea3f9d431852747f/src/ui/media-devices.js#L19-L21

... and whether it supports recording a camera of some kind:

https://github.com/elan-ev/opencast-studio/blob/d52b01eb3e496d1092ff1869ea3f9d431852747f/src/ui/media-devices.js#L33-L35

If one is not supported, the UI element for that source is not shown. *However*, these tests only check if the browser API exists and not if recording is actually supported. For example, in the current FF or Chrome on Android, the API exists (and thus both methods return `true`), but the feature is still not supported. 

I have researched how one would check if screen recording is supported but haven't found an answer yet. As the whole API is not yet standardized and pretty new, there might not be a good solution. I also asked [on StackOverflow](https://stackoverflow.com/q/58842831/2408867). Maybe we just need to manually check the user agent and apply some metrics.
