### ISSUE TITLE
Tracking issue: support for iOS/MacOS, Safari

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#84]
Currently, Safari supports `getUserMedia` (webcam), does *not* support `getDisplayMedia` (screen) and partially supports `MediaRecorder`. The important part is tracking the `MediaRecorder` support for now.

Current state:
- `MediaRecorder` support exists in Safari, but is experimental and must be manually enabled in the browser's settings
- Users reported Safari on iOS to _cresh_ after approximately 10min, causing the recording to be lost. Shorter recordings seem to work.
- Mobile Safari always uses the front face camera without asking. See issue #217  
- Video is rotated by 180° in recording

Useful links:
- [caniuse link for MediaRecorder](https://caniuse.com/#feat=mediarecorder)
- [Related changes in Safari's SVN repo](https://trac.webkit.org/log/webkit/trunk/Source/WebCore/Modules/mediarecorder)

**Comment by luniki** [comment]
see #86

**Comment by lkiesow** [comment]
Not sure what the relation between this and #86 is except that both issues appear on iOS.

**Comment by luniki** [comment]
I tested this on an iPad running Safari 13.x with an enabled "Experimental Setting" >> "MediaRecorder" and it does work as advertised.

**Comment by lkiesow** [comment]
I'm not sure if I understand this correctly. If I remember correctly, iOS worked right at the beginning and some later change broke it right? So, it can generally work without the experimental flag, right?

Having users manually enable an experimental flag in the settings (that's what you want them to do, correct?) is a usability nightmare. We need to find a way around that.

**Comment by luniki** [comment]
> I'm not sure if I understand this correctly. If I remember correctly, iOS worked right at the beginning and some later change broke it right? So, it can generally work without the experimental flag, right?

According to [caniuse](https://caniuse.com/#feat=mediarecorder) this should never have worked. To prove this I setup the old version of OC Studio and tested it with an iPad but it does not work (as expected). 

I searched through the WebKit Bugzilla finding this one: (#85851)[https://bugs.webkit.org/show_bug.cgi?id=85851#c43]

So even after Safari released the new Version v13, MediaRecorder still does not work without the experimental flag…

> Having users manually enable an experimental flag in the settings (that's what you want them to do, correct?) is a usability nightmare. We need to find a way around that.

You are right. This is a nightmare. But I fear that we cannot find a workaround other than waiting for Apple to fix the problem some day.

**Comment by LukasKalbertodt** [comment]
This indeed seems to be impossible right now. I also searched for poly fills, but the ones I found only support audio recording. Developing an own polyfill is probably overkill.

**Comment by LukasKalbertodt** [comment]
I just tested this with the experimental flag and the video seems to be rotated by 180°. Not the preview, just the resulting video. 

Also: I'd propose to keep this issue open as a tracking issue until iOS is supported.

**Comment by LukasKalbertodt** [comment]
I think this can be closed. Safari now (>= 14) supports the `MediaRecorder` API and all other APIs we require. https://github.com/elan-ev/opencast-studio/pull/935 updates the browser table. It's still suboptimal, but all problems are tracked by other issues, e.g. #517 and #934, or are problems that Studio can definitely not fix.
