### ISSUE TITLE
Zooming does not always work on iOS

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#85]
I found that zooming on iOS sometimes works and sometimes not. If it did not, entering a text box would usually fix that problem. Zooming is a very helpful accessibility feature and should work if possible.

![VID_20191014_134802 mp4-2](https://user-images.githubusercontent.com/1008395/66787104-bfd5f300-eee2-11e9-96a7-c94893924e64.gif)

**Comment by luniki** [comment]
I tried reproducing this on my test iPad in Safari and Firefox but was not successful

**Comment by LukasKalbertodt** [comment]
I also tried reproducing this. I can zoom fine on all pages. Only thing I could not test is the post-record dialog (as recording does not work yet). So I guess we can close this for now.
