### ISSUE TITLE
Footer not accessible on iOS

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#86]
On iOS, you cannot scroll down to the footer to access the links placed down there:

<img src="https://user-images.githubusercontent.com/1008395/66787244-3d016800-eee3-11e9-8c0d-c3c7f1b2be1b.gif" width="400"/>

**Comment by lkiesow** [comment]
@LukasKalbertodt, assigning this to you since you are looking at a new layout anyway.

**Comment by LukasKalbertodt** [comment]
While the layout is not perfect yet, the full page is visible on all devices I tested with. For iOS, I tested on the office iPad. So I'm closing this issue.
