### ISSUE TITLE
Lost, empty space in dialogs

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#88]
Most input dialogs have a lot of empty space with all of the functional elements pressed to the left side even on small devices like smartphones. If possible, we should make better use of this place and e.g. choose a two-column layout if we have sufficient space or make the input boxes reach over the whole with:

###### We use half of this dialog's space
<img src="https://user-images.githubusercontent.com/1008395/66787452-0a0ba400-eee4-11e9-9f9d-803a0de51b35.png" width="300"/>

###### Even on Android we could put the descriptions left of the input fields
<img src="https://user-images.githubusercontent.com/1008395/66787702-f01e9100-eee4-11e9-80ff-1ae23bb3d1ff.jpg" width="300"/>

**Comment by luniki** [comment]
Enlarging the text input fields is def necessary.

Having the label top aligned is a UI best practice. See for example: https://www.uxmatters.com/mt/archives/2006/07/label-placement-in-forms.php

Two-column layouts should be used (almost) never. See "One Column vs. Multiple Columns" in: https://uxplanet.org/designing-more-efficient-forms-structure-inputs-labels-and-actions-e3a47007114f
