### ISSUE TITLE
Studio should gracefully handle URLs with and without trailing slash

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#91]
- https://develop.opencast.org/ is accepted by Studio
- https://develop.opencast.org is **not** accepted by Studio
…that's not acceptable :wink: 

<img src="https://user-images.githubusercontent.com/1008395/66788386-ae431a00-eee7-11e9-8860-b8b57b946625.png" width="300"/>

**Comment by rockysantiago** [comment]
Please assign this to me.
