### ISSUE TITLE
“about us” vs “About Opencast Studio”

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#92]
We have two “about” link which link to totally different places:

- “About Opencast Studio” links to the about page
- “about us” in the footer links to the impressum which is kind of confusing. 

Even in English, it's not uncommon for German sites to use the word “Impressum” as a legal term since it does reference German law after all. If we want something else then “Legal notices” might do. “About us” is just confusing.

**Comment by callmeanto** [comment]
So I just have to change the word "About us" to "Legal Notices"?
