### ISSUE TITLE
Specify source selection workflow

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#93]
- It's not explained anywhere how audio works
- Recording just one stream (screen or webcam) must also record audio

**Comment by luniki** [comment]
Not every browser is able to record audio while screen recording. ( https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia#Browser_compatibility )

The whole workflow of choosing the sources of recordings has to be refactored.

We will have to specify that new workflow together.

**Comment by luniki** [comment]
This could be done on another page too (see #18 and #182)

**Comment by LukasKalbertodt** [comment]
This can be closed now that #188 landed, right?

**Comment by LukasKalbertodt** [comment]
As no one said otherwise, I will close this now as I think this issue is either fixed or completely outdated.
