### ISSUE TITLE
Update supported browsers + OS combination in documentation

### ISSUE THREAD

**Issue by cgruber-uos** [elan-ev/opencast-studio#930]
On the table **Supported Browsers** at https://github.com/elan-ev/opencast-studio/blob/master/README.md#supported-browsers Win10 is only listed as OS. There is **no Win11** + browser combination on this page. 

Is there a test protocol what has to be done to get a ✓ for a working OS--browser combination? So I can do this.

**Comment by LukasKalbertodt** [comment]
The table is a bit outdated and lacking in several regards, unfortunately. It basically hasn't been touched for two years or so. There is not really a "test protocol" per se. Mostly clicking through the app once, trying every feature and see if it works. If you could do that for Win11 for the three major browsers, that would be sweet! (I do expect it to fully work, exactly like with win10)

However, I would consider replacing the table with something else. By now most browser/OS combinations work with Studio, so it might be better just listing problematic cases. If you want to test for win 11, could you just report back here on this issue? Then I will adjust this section of the README accordingly.

**Comment by cgruber-uos** [comment]
I have tested https://studio.opencast.org/ [2021-05-17] with Win11 and Chrome 101, FF 100, Edge 101 capturing audio, cam, screen was possible, also cutting and downloading the video(s). I don't konw if #517 should affect testing or if it is a workaround build in right now. Opening the `*.webm` file was possible, but I could not jump to a certain point on the scrubber. So it sounds like #517 is still there. I wonder about the linked table. There is no remark about #517 with the combination Win + FF, so it indicates that it works?? With Win11 and FF100 the scrubber problematic still exists on downloaded videos, so I would assume that it did not work before. Jumping via clicking on the scrubber in the studio UI an the preview page was possible without any problem.

**Comment by LukasKalbertodt** [comment]
Thanks a ton for testing!

> There is no remark about https://github.com/elan-ev/opencast-studio/issues/517 with the combination Win + FF, so it indicates that it works?? With Win11 and FF 100 the scrubber problematic still exists on downloaded videos, so I would assume that it did not work before.

That's strange. With FF on Win 10 (or Linux), it is possible to seek through the downloaded video. It would be very unexpected and strange if FF would behave differently on Win 11. Can you maybe... try that again? And if you can still not seek around, could you send the video file to kalbertodt@elan-ev.de? I'd be interested in checking it out.

> Jumping via clicking on the scrubber in the studio UI an the preview page was possible without any problem.

Yeah, that works due to a workaround that we employed. 

---

I will update the browser compatibility section in the README soon!

**Comment by cgruber-uos** [comment]
> Can you maybe... try that again? And if you can still not seek around, could you send the video file to [kalbertodt@elan-ev.de](mailto:kalbertodt@elan-ev.de)?

It's not working on Win11 and FF100.x I sent you the test video.
