### ISSUE TITLE
Capturing "Display & Camera" does not work in Safari (macOS)

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/opencast-studio#934]
When pressing the "Display & Capture"-button in Safari on macOS I'm not asked for permission to share my screen. Instead, I see the following error.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/123272/170961776-6dc4dc12-1120-4b01-ae9c-b6f6c8526c2a.png">

Camera capture works just fine, as does capturing *only* the screen (using the "Display" button in the first step).

The following error is logged to the console on the screen seen in the screenshot:

```
[Error] Error: InvalidAccessError: getDisplayMedia must be called from a user gesture handler.
	(anonymous function) (2.859294be.chunk.js:2:305924)
	(anonymous function) (4.58adb615.chunk.js:1:12044)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
```

(Everything tested on https://studio.opencast.org.)

**Comment by lkiesow** [comment]
Safari [does now seem to support `getDisplayMedia`](https://caniuse.com/?search=getDisplayMedia).

**Comment by LukasKalbertodt** [comment]
@JulianKniephoff Can you test whether it works now, especially with the redesign?

**Comment by JulianKniephoff** [comment]
<img width="1136" alt="image" src="https://github.com/elan-ev/opencast-studio/assets/123272/52d9ae19-41f2-4c9b-9d79-b78e2e5b608f">
