### ISSUE TITLE
Consistant color for focused buttons / download button is atm different

### ISSUE THREAD

**Issue by cgruber-uos** [elan-ev/opencast-studio#940]
While testing the new introduced tab navigation (see #629) I noticed a different behavior of all next buttons vs. the download button on the final side: 

All bottom right "next" buttons stay green while focusing with a wider also green border when focused: 

![2022-06-02 22_47_05-](https://user-images.githubusercontent.com/101632236/171736988-f0e0257d-9b7d-4787-9342-7f3183f8a288.png)

But the download button is different: While tabbing and focusing it color changes to white and black text: 

![2022-06-02 22_47_49-Greenshot](https://user-images.githubusercontent.com/101632236/171737120-0e1c1fea-ce1a-4bf1-b83a-65dc29663cf0.png)

This is not bad and perhaps the better solution than adding a green border to a green button. But it should be consistent for all similar UI elements. A download link is technically an other element than a button, but I think for a user it is more or less the same.

**Comment by lkiesow** [comment]
+1 for making this a green button as well.
Soonish, the new design is coming anyway, but no need to wait for that to fix this small inconsistency.

**Comment by naweidner** [comment]
Fixed with commit [435cac1](https://github.com/elan-ev/opencast-studio/pull/932/commits/435cac1460a580668cf00e50625a4aa99db38b1e)
