### ISSUE TITLE
Feature: Force assignment of series

### ISSUE THREAD

**Issue by mtneug** [elan-ev/opencast-studio#967]
We would like for every video to be part of a series. If no series ID is given, it would be great if Opencast Studio could (create and) assign a default series for the current user (e.g. `Opencast Studio recordings of Matthias`).

**Comment by LukasKalbertodt** [comment]
This rather feels like something Opencast should do. It would require Studio to use more APIs of Opencast (which is not great and people need to give appropriate permissions to all users using Studio). But also, this solves the problem only for Studio: what about all other means of uploading a video to Opencast, e.g. Tobira or LMSes or ...? The logic of creating a user series and assigning the video to it would have to be implemented in all those tools. And good luck getting the behavior consistent between all those tools (e.g. the name of the user series). 

So I would very much prefer to not add this to Studio. Or is there a good reason that I'm not seeing? I guess it might be hard configuring this logic in Opencast right now?

<details>
<summary>And as an aside...</summary>

I think what you are actually trying to do here should be solved differently. Like, with a proper "ownership" model or something like that, where uploaded videos are associated with a user. Creating a "user series" already feels like a hack/workaround. 
</details>

**Comment by mtneug** [comment]
> I think what you are actually trying to do here should be solved differently. Like, with a proper "ownership" model or something like that, where uploaded videos are associated with a user. Creating a "user series" already feels like a hack/workaround.

Sorry for starting with the site note :D. I'm not trying to implement ownership with this. We use ACLs for this.

> what about all other means of uploading a video to Opencast, e.g. Tobira or LMSes or ...?

In our Opencast instance (as well as others I know), every video **must** be part of a series. ILIAS and Moodle already do this, and in the Admin UI this is a required field. I don't know about Tobira, so for us, OC Studio is the only one missing.

> So I would very much prefer to not add this to Studio. Or is there a good reason that I'm not seeing? I guess it might be hard configuring this logic in Opencast right now?

Yes and no. The `series` operation can attach a series to an event. The question is how to create/find the series. This could be done with a custom exec operation, though. I agree that this would be the most generic solution. I will try to implement this in our workflows.

Closing this for now.
