### ISSUE TITLE
Don't cutoff title if there is place on the page

### ISSUE THREAD

**Issue by mtneug** [elan-ev/opencast-studio#971]
The title is cut off if 500px are not enough to display it even if there is still place on the page:

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/3051721/197201718-7fabdcbc-261f-46ab-920c-9820547581e4.png">

**Comment by LukasKalbertodt** [comment]
Where is that screenshot from exactly? From what step in Studio? I don't think the title (which is only chosen in the last step) is ever shown above the video?

**Comment by mtneug** [comment]
oh this is the editor and not studio 🤦  sorry for the confusion.
